// registry/react/components/environment-switcher-card/EnvironmentSwitcherCard.tsx
import { useState, type HTMLAttributes } from "react";
import { Autocomplete } from "../ui/Autocomplete";
import { Badge } from "../ui/Badge";
import { Button } from "../ui/Button";
import { CompositionRoot } from "./_CompositionRoot";
import type { CompositionSurfaceProps } from "./composition";

const defaultEnvironments: readonly string[] = [
  "atlas-production",
  "atlas-preview",
  "atlas-staging",
  "relay-production",
  "relay-preview",
  "harbor-production",
  "harbor-development",
  "nova-development",
  "quill-preview",
];

export interface EnvironmentSwitcherCardProps
  extends Omit<HTMLAttributes<HTMLDivElement>, "title" | "color">, CompositionSurfaceProps {
  "data-balsa"?: string;
  title?: string;
  description?: string;
  environments?: readonly string[];
  onSwitch?: (environment: string) => void;
}

export function EnvironmentSwitcherCard({
  title = "Switch environment",
  description = "Everything below applies to the one you pick.",
  environments = defaultEnvironments,
  headingLevel,
  shadow,
  theme,
  onSwitch,
  "data-balsa": _dataBalsa,
  ...domProps
}: EnvironmentSwitcherCardProps) {
  void _dataBalsa;
  const [target, setTarget] = useState("atlas-production");

  return (
    <CompositionRoot
      {...domProps}
      title={title}
      description={description}
      headingLevel={headingLevel}
      shadow={shadow}
      theme={theme}
      data-composition="environment-switcher"
      action={<Badge color="primary" variant="soft">Live</Badge>}
    >
      <div className="flex flex-1 flex-col justify-between gap-balsa-lg">
        <Autocomplete
          id="environment-target"
          value={target}
          onValueChange={(value) => {
            if (typeof value === "string") setTarget(value);
          }}
          label="Environment"
          suggestions={environments}
          placeholder="Start typing a project or environment"
          hint="Nine environments across five projects."
        />
        <Button className="w-full" onClick={() => onSwitch?.(target)}>
          Switch to this environment
        </Button>
      </div>
    </CompositionRoot>
  );
}

// src/components/compositions/EnvironmentSwitcherCard.vue
<script setup lang="ts">
import { ref } from "vue";
import Autocomplete from "../ui/Autocomplete.vue";
import Badge from "../ui/Badge.vue";
import Button from "../ui/Button.vue";
import CompositionRoot from "./_CompositionRoot.vue";
import type { CompositionSurfaceProps } from "./composition";

/**
 * Search across more environments than a menu should hold, with the current one
 * stated rather than implied. One unit: choosing where you are working is a
 * small decision that should not take a screen.
 */
const props = withDefaults(defineProps<CompositionSurfaceProps & {
  title?: string;
  description?: string;
  environments?: readonly string[];
}>(), {
  title: "Switch environment",
  description: "Everything below applies to the one you pick.",
  environments: () => [
    "atlas-production", "atlas-preview", "atlas-staging",
    "relay-production", "relay-preview",
    "harbor-production", "harbor-development",
    "nova-development", "quill-preview",
  ],
});
const emit = defineEmits<{ switch: [environment: string] }>();

const target = ref("atlas-production");
</script>

<template>
  <CompositionRoot v-bind="props" data-composition="environment-switcher">
    <template #action><Badge color="primary" variant="soft">Live</Badge></template>
    <div class="flex flex-1 flex-col justify-between gap-balsa-lg">
      <Autocomplete
        id="environment-target"
        v-model="target"
        label="Environment"
        :suggestions="props.environments"
        placeholder="Start typing a project or environment"
        hint="Nine environments across five projects."
      />
      <Button class="w-full" @click="emit('switch', target)">Switch to this environment</Button>
    </div>
  </CompositionRoot>
</template>
