// registry/react/components/payment-method-card/PaymentMethodCard.tsx
import { Plus } from "lucide-react";
import { useState, type HTMLAttributes } from "react";
import { Button } from "../ui/Button";
import { RadioGroup, type RadioGroupOption } from "../ui/RadioGroup";
import { CompositionRoot } from "./_CompositionRoot";
import type { CompositionSurfaceProps } from "./composition";

const defaultMethods: readonly RadioGroupOption[] = [
  { label: "Card on file", value: "card", description: "Charged on the first of each month" },
  { label: "Invoice", value: "invoice", description: "Net 30, sent to billing@example.com" },
  { label: "Prepaid credits", value: "credits", description: "4,200 credits remaining" },
];

export interface PaymentMethodCardProps extends Omit<HTMLAttributes<HTMLDivElement>, "title" | "color">, CompositionSurfaceProps {
  "data-balsa"?: string;
  title?: string;
  description?: string;
  methods?: readonly RadioGroupOption[];
  onContinue?: (method: string) => void;
}

export function PaymentMethodCard({
  title = "Billing method",
  description = "How this workspace is invoiced.",
  methods = defaultMethods,
  headingLevel,
  shadow,
  theme,
  onContinue,
  "data-balsa": _dataBalsa,
  ...domProps
}: PaymentMethodCardProps) {
  void _dataBalsa;
  const [method, setMethod] = useState(methods[0]?.value || "");

  return (
    <CompositionRoot
      {...domProps}
      title={title}
      description={description}
      headingLevel={headingLevel}
      shadow={shadow}
      theme={theme}
      data-composition="payment-method"
      footer={
        <Button className="w-full" disabled={!method} onClick={() => onContinue?.(method)}>
          Save billing method
        </Button>
      }
    >
      <RadioGroup
        id="payment-method"
        label="Saved methods"
        options={methods}
        layout="cards"
        className="w-full"
        value={method}
        onValueChange={setMethod}
      />
      <Button className="mt-balsa-lg w-full" variant="soft" prefixIcon={Plus} onClick={() => setMethod("")}>
        Add another method
      </Button>
      <dl className="mt-balsa-xl divide-y divide-balsa-border rounded-balsa-control bg-balsa-muted px-balsa-md text-sm">
        <div className="flex justify-between py-balsa-md">
          <dt>Next invoice</dt>
          <dd className="tabular-nums">Sep 1, 2026</dd>
        </div>
        <div className="flex justify-between py-balsa-md">
          <dt>Estimated</dt>
          <dd className="tabular-nums">$297.00</dd>
        </div>
        <div className="flex justify-between py-balsa-md">
          <dt>Billing contact</dt>
          <dd className="truncate">billing@example.com</dd>
        </div>
      </dl>
    </CompositionRoot>
  );
}

// src/components/compositions/PaymentMethodCard.vue
<script setup lang="ts">
import { Plus } from "@lucide/vue";
import { ref } from "vue";
import Button from "../ui/Button.vue";
import RadioGroup, { type RadioGroupOption } from "../ui/RadioGroup.vue";
import CompositionRoot from "./_CompositionRoot.vue";
import type { CompositionSurfaceProps } from "./composition";

const props = withDefaults(defineProps<CompositionSurfaceProps & { title?: string; description?: string; methods?: readonly RadioGroupOption[] }>(), {
  title: "Billing method", description: "How this workspace is invoiced.", methods: () => [
    { label: "Card on file", value: "card", description: "Charged on the first of each month" },
    { label: "Invoice", value: "invoice", description: "Net 30, sent to billing@example.com" },
    { label: "Prepaid credits", value: "credits", description: "4,200 credits remaining" },
  ],
});
const emit = defineEmits<{ continue: [method: string] }>();
const method = ref(props.methods[0]?.value || "");
</script>

<template>
  <CompositionRoot v-bind="props" data-composition="payment-method">
    <RadioGroup id="payment-method" v-model="method" label="Saved methods" :options="props.methods" layout="cards" class="w-full" />
    <Button class="mt-balsa-lg w-full" variant="soft" :prefix-icon="Plus" @click="method = ''">Add another method</Button>
    <dl class="mt-balsa-xl divide-y divide-balsa-border rounded-balsa-control bg-balsa-muted px-balsa-md text-sm">
      <div class="flex justify-between py-balsa-md"><dt>Next invoice</dt><dd class="tabular-nums">Sep 1, 2026</dd></div>
      <div class="flex justify-between py-balsa-md"><dt>Estimated</dt><dd class="tabular-nums">$297.00</dd></div>
      <div class="flex justify-between py-balsa-md"><dt>Billing contact</dt><dd class="truncate">billing@example.com</dd></div>
    </dl>
    <template #footer><Button class="w-full" :disabled="!method" @click="emit('continue', method)">Save billing method</Button></template>
  </CompositionRoot>
</template>
