// packages/react/src/components/compositions/SettingsCard.tsx
import { useState, type HTMLAttributes } from "react";
import { Button } from "../ui/Button";
import { Select, type SelectOption } from "../ui/Select";
import { Switch } from "../ui/Switch";
import { CompositionRoot } from "./_CompositionRoot";
import type { CompositionSurfaceProps } from "./composition";

export interface SettingsCardValue {
  locale: string;
  analytics: boolean;
}

export interface SettingsCardProps extends Omit<HTMLAttributes<HTMLDivElement>, "title" | "color">, CompositionSurfaceProps {
  "data-balsa"?: string;
  title?: string;
  description?: string;
  onSave?: (value: SettingsCardValue) => void;
  onReset?: () => void;
}

const options: readonly SelectOption[] = [
  { label: "English (United States)", value: "en" },
  { label: "Português (Brasil)", value: "pt" },
];

export function SettingsCard({
  title = "Workspace settings",
  description = "Manage defaults and product behavior.",
  headingLevel,
  shadow,
  theme,
  onSave,
  onReset,
  "data-balsa": _dataBalsa,
  ...domProps
}: SettingsCardProps) {
  void _dataBalsa;
  const [locale, setLocale] = useState("en");
  const [analytics, setAnalytics] = useState(true);

  return (
    <CompositionRoot
      {...domProps}
      title={title}
      description={description}
      headingLevel={headingLevel}
      shadow={shadow}
      theme={theme}
      data-composition="settings"
      footer={
        <div className="flex justify-between gap-balsa-md">
          <Button variant="soft" onClick={onReset}>Reset</Button>
          <Button onClick={() => onSave?.({ locale, analytics })}>Save settings</Button>
        </div>
      }
    >
      <div className="grid flex-1 content-between gap-balsa-xl">
        <Select
          id="settings-locale"
          value={locale}
          label="Default language"
          options={options}
          onValueChange={(value) => {
            if (typeof value === "string") setLocale(value);
          }}
        />
        <div className="border-balsa-border pt-balsa-lg [border-top-width:var(--balsa-border-width)]">
          <Switch
            id="settings-analytics"
            checked={analytics}
            label="Usage analytics"
            hint="Share anonymous activity to improve workspace recommendations."
            onCheckedChange={setAnalytics}
          />
        </div>
      </div>
    </CompositionRoot>
  );
}

// src/components/compositions/SettingsCard.vue
<script setup lang="ts">
import { ref } from "vue";
import Button from "../ui/Button.vue";
import Select, { type SelectOption } from "../ui/Select.vue";
import Switch from "../ui/Switch.vue";
import CompositionRoot from "./_CompositionRoot.vue";
import type { CompositionSurfaceProps } from "./composition";

const props = withDefaults(defineProps<CompositionSurfaceProps & { title?: string; description?: string }>(), { title: "Workspace settings", description: "Manage defaults and product behavior." });
const emit = defineEmits<{ save: [{ locale: string; analytics: boolean }]; reset: [] }>();
const locale = ref("en");
const analytics = ref(true);
const options: readonly SelectOption[] = [{ label: "English (United States)", value: "en" }, { label: "Português (Brasil)", value: "pt" }];
</script>

<template>
  <CompositionRoot v-bind="props" data-composition="settings">
    <div class="grid flex-1 content-between gap-balsa-xl">
      <Select id="settings-locale" v-model="locale" label="Default language" :options="options" />
      <div class="border-t-(length:--balsa-border-width) border-balsa-border pt-balsa-lg"><Switch id="settings-analytics" v-model="analytics" label="Usage analytics" hint="Share anonymous activity to improve workspace recommendations." /></div>
    </div>
    <template #footer><div class="flex justify-between gap-balsa-md"><Button variant="soft" @click="emit('reset')">Reset</Button><Button @click="emit('save', { locale, analytics })">Save settings</Button></div></template>
  </CompositionRoot>
</template>
