// src/components/compositions/DeviceVerificationCard.vue
<script setup lang="ts">
import { computed, ref } from "vue";
import Button from "../ui/Button.vue";
import InputOTP from "../ui/InputOTP.vue";
import Link from "../ui/Link.vue";
import CompositionRoot from "./_CompositionRoot.vue";
import type { CompositionSurfaceProps } from "./composition";

/**
 * One task, one control, one confirmation. A verification step is a whole
 * screen in production and still only a single unit here, because padding it
 * out with detail would misrepresent how little should be on it.
 */
const props = withDefaults(defineProps<CompositionSurfaceProps & {
  title?: string;
  description?: string;
  length?: number;
}>(), {
  title: "Confirm this device",
  description: "Enter the six digits sent to ada@example.com.",
  length: 6,
});
const emit = defineEmits<{ verify: [code: string]; resend: [] }>();

const code = ref("");
const complete = computed(() => code.value.length === props.length);
</script>

<template>
  <CompositionRoot v-bind="props" data-composition="device-verification">
    <InputOTP
      id="device-code"
      v-model="code"
      label="Verification code"
      :length="props.length"
      grouped
      fluid
      :separator-every="3"
    />
    <p class="mt-balsa-lg text-xs text-balsa-muted-foreground">
      The code expires in 10 minutes.
      <Link href="#" @click.prevent="emit('resend')">Send it again</Link>
    </p>
    <template #footer>
      <Button class="w-full" :disabled="!complete" @click="emit('verify', code)">Verify device</Button>
    </template>
  </CompositionRoot>
</template>

// registry/react/components/device-verification-card/DeviceVerificationCard.tsx
import { useState, type HTMLAttributes, type MouseEvent } from "react";
import { Button } from "../ui/Button";
import { InputOTP } from "../ui/InputOTP";
import { Link } from "../ui/Link";
import { CompositionRoot } from "./_CompositionRoot";
import type { CompositionSurfaceProps } from "./composition";

export interface DeviceVerificationCardProps extends Omit<HTMLAttributes<HTMLDivElement>, "title" | "color">, CompositionSurfaceProps {
  "data-balsa"?: string;
  title?: string;
  description?: string;
  length?: number;
  onVerify?: (code: string) => void;
  onResend?: () => void;
}

export function DeviceVerificationCard({
  title = "Confirm this device",
  description = "Enter the six digits sent to ada@example.com.",
  length = 6,
  headingLevel,
  shadow,
  theme,
  onVerify,
  onResend,
  "data-balsa": _dataBalsa,
  ...domProps
}: DeviceVerificationCardProps) {
  void _dataBalsa;
  const [code, setCode] = useState("");
  const complete = code.length === length;

  function handleResend(event: MouseEvent<HTMLAnchorElement>) {
    event.preventDefault();
    onResend?.();
  }

  return (
    <CompositionRoot
      {...domProps}
      title={title}
      description={description}
      headingLevel={headingLevel}
      shadow={shadow}
      theme={theme}
      data-composition="device-verification"
      footer={(
        <Button className="w-full" disabled={!complete} onClick={() => onVerify?.(code)}>
          Verify device
        </Button>
      )}
    >
      <InputOTP
        id="device-code"
        value={code}
        onValueChange={setCode}
        label="Verification code"
        length={length}
        grouped
        fluid
        separatorEvery={3}
      />
      <p className="mt-balsa-lg text-xs text-balsa-muted-foreground">
        The code expires in 10 minutes.{" "}
        <Link href="#" onClick={handleResend}>Send it again</Link>
      </p>
    </CompositionRoot>
  );
}
