// src/components/ui/DropdownMenu.vue
<script setup lang="ts">
import {
  computed,
  nextTick,
  onBeforeUnmount,
  onMounted,
  ref,
  useAttrs,
  watch,
} from "vue";
import {
  getAnchoredLayerPosition,
  type AnchoredAlign,
  type AnchoredSide,
} from "./anchored-layer";
import { mergeClasses } from "./classes";
import type { Rounded } from "./form";
import MenuList from "./MenuList.vue";
import type { MenuItem, MenuSelection, MenuVariant } from "./menu";
import type { Shadow, ThemeInput } from "./theme";
import type { ActionColor } from "./types";
import { useResolvedThemeProps } from "./theme-context";

defineOptions({ inheritAttrs: false });

const rawProps = withDefaults(
  defineProps<{
    id: string;
    label: string;
    items: readonly MenuItem[];
    side?: AnchoredSide;
    align?: AnchoredAlign;
    sideOffset?: number;
    variant?: MenuVariant;
    color?: ActionColor;
    rounded?: Rounded;
    shadow?: Shadow;
    contained?: boolean;
    disabled?: boolean;
    theme?: ThemeInput;
  }>(),
  {
    side: "bottom",
    align: "start",
    sideOffset: 8,
    color: "primary",
    contained: false,
    disabled: false,
  },
);
const { props, theme } = useResolvedThemeProps(
  "dropdown-menu",
  "overlays",
  rawProps,
  { variant: "surface", rounded: "lg", shadow: "auto" } as const,
);

const emit = defineEmits<{
  select: [selection: MenuSelection];
}>();
const model = defineModel<boolean>({ default: false });
const attrs = useAttrs();
const root = ref<HTMLElement | null>(null);
const portalPresentation = computed(() => theme.presentationForPortal(root.value));
const trigger = ref<HTMLButtonElement | null>(null);
const layer = ref<HTMLElement | null>(null);
const list = ref<{ focusFirst: () => void } | null>(null);
const resolvedPalette = ref<string>();
const resolvedSide = ref<AnchoredSide>(props.side);
const position = ref({ left: 0, top: 0, maxHeight: 0 });

const triggerClasses = computed(() =>
  mergeClasses(
    "inline-flex min-h-9 cursor-pointer items-center justify-center gap-2 rounded-lg border border-balsa-border-strong bg-balsa-surface px-3 py-1.5 text-sm font-semibold text-balsa-surface-foreground transition-colors hover:bg-balsa-muted focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-balsa-focus-ring disabled:cursor-not-allowed disabled:bg-balsa-disabled disabled:text-balsa-disabled-foreground",
    attrs.class,
  ),
);
const layerClasses = computed(() => [
  "z-[65]",
  props.contained ? "absolute" : "fixed",
]);
const layerStyle = computed(() => ({
  left: `${position.value.left}px`,
  top: `${position.value.top}px`,
  maxHeight: `${position.value.maxHeight}px`,
}));

function resolveContext(): void {
  resolvedPalette.value = typeof attrs["data-palette"] === "string"
    ? attrs["data-palette"]
    : root.value?.closest<HTMLElement>("[data-palette]")?.dataset.palette;
}

function updatePosition(): void {
  if (!trigger.value || !layer.value || !model.value) return;
  const next = getAnchoredLayerPosition(trigger.value, layer.value, {
    side: props.side,
    align: props.align,
    sideOffset: props.sideOffset,
    alignOffset: 0,
  });
  const rootRect = root.value?.getBoundingClientRect();
  position.value = {
    left: next.left - (props.contained ? rootRect?.left ?? 0 : 0),
    top: next.top - (props.contained ? rootRect?.top ?? 0 : 0),
    maxHeight: next.maxHeight,
  };
  resolvedSide.value = next.side;
}

function close(restoreFocus = true): void {
  model.value = false;
  if (restoreFocus) void nextTick(() => trigger.value?.focus());
}

function handleSelection(selection: MenuSelection): void {
  emit("select", selection);
  close();
}

function handleDocumentPointer(event: PointerEvent): void {
  if (!model.value) return;
  const target = event.target as Node;
  if (root.value?.contains(target) || layer.value?.contains(target)) return;
  close(false);
}

function handleTriggerKeydown(event: KeyboardEvent): void {
  if (["ArrowDown", "Enter", " "].includes(event.key)) {
    event.preventDefault();
    model.value = true;
  } else if (event.key === "ArrowUp") {
    event.preventDefault();
    model.value = true;
    void nextTick(() => {
      const buttons = layer.value?.querySelectorAll<HTMLElement>('[role^="menuitem"]');
      buttons?.item(buttons.length - 1)?.focus();
    });
  }
}

watch(
  [model, () => props.side, () => props.align, () => props.theme],
  async ([open]) => {
    resolveContext();
    if (!open) return;
    await nextTick();
    updatePosition();
    list.value?.focusFirst();
  },
  { immediate: true },
);

onMounted(() => {
  resolveContext();
  document.addEventListener("pointerdown", handleDocumentPointer, true);
  window.addEventListener("resize", updatePosition, { passive: true });
  window.addEventListener("scroll", updatePosition, true);
});

onBeforeUnmount(() => {
  document.removeEventListener("pointerdown", handleDocumentPointer, true);
  window.removeEventListener("resize", updatePosition);
  window.removeEventListener("scroll", updatePosition, true);
});
</script>

<template>
  <span
    ref="root"
    data-balsa="dropdown-menu"
    :data-theme="theme.explicitPresentation.value?.id"
    :data-theme-base="theme.explicitPresentation.value?.base"
    :style="theme.explicitPresentation.value?.style"
    :data-palette="typeof attrs['data-palette'] === 'string' ? attrs['data-palette'] : undefined"
    :data-color="props.color"
    :data-rounded="props.rounded"
    :data-state="model ? 'open' : 'closed'"
    class="relative inline-flex"
  >
    <button
      :id="`${props.id}-trigger`"
      ref="trigger"
      type="button"
      :disabled="props.disabled"
      :aria-expanded="model"
      :aria-controls="props.id"
      aria-haspopup="menu"
      :class="triggerClasses"
      @click="model = !model"
      @keydown="handleTriggerKeydown"
    >
      <slot name="trigger">Open menu</slot>
    </button>

    <Teleport to="body" :disabled="props.contained">
      <Transition
        enter-active-class="transition-[opacity,transform] duration-150 ease-out"
        enter-from-class="translate-y-1 opacity-0"
        leave-active-class="transition-[opacity,transform] duration-100 ease-in"
        leave-to-class="translate-y-1 opacity-0"
      >
        <div
          v-if="model"
          ref="layer"
          :data-theme="portalPresentation.id"
          :data-theme-base="portalPresentation.base"
          :data-palette="resolvedPalette"
          :data-side="resolvedSide"
          :data-shadow="props.shadow"
          :class="layerClasses"
          :style="[layerStyle, portalPresentation.style]"
        >
          <MenuList
            :id="props.id"
            ref="list"
            :label="props.label"
            :items="props.items"
            :variant="props.variant"
            :color="props.color"
            :rounded="props.rounded"
            :theme="theme.input.value"
            :palette="resolvedPalette"
            @select="handleSelection"
            @dismiss="close"
          />
        </div>
      </Transition>
    </Teleport>
  </span>
</template>

// packages/react/src/components/ui/DropdownMenu.tsx
import {
  useLayoutEffect,
  useRef,
  useState,
  type CSSProperties,
  type HTMLAttributes,
  type KeyboardEvent,
  type ReactNode,
} from "react";
import { createPortal } from "react-dom";
import {
  getAnchoredLayerPosition,
  type AnchoredAlign,
  type AnchoredSide,
} from "./anchored-layer";
import { useBalsaPortalScope } from "./BalsaPortalScope";
import { Button } from "./Button";
import { mergeClasses } from "./classes";
import { roundedClasses, type Rounded } from "./form";
import { MenuList, type MenuListHandle } from "./MenuList";
import type { MenuItem, MenuSelection, MenuVariant } from "./menu";
import {
  capturePortalPresentation,
  type PortalPresentationSnapshot,
} from "./portal-core";
import type { Shadow, ThemeInput, ThemePresentation } from "./theme";
import {
  BalsaThemeContext,
  useControllableState,
  useResolvedThemeProps,
} from "./theme-context";
import type { ActionColor } from "./types";

export interface DropdownMenuProps extends Omit<
  HTMLAttributes<HTMLElement>,
  "children" | "id" | "onSelect"
> {
  id: string;
  label: string;
  items: readonly MenuItem[];
  side?: AnchoredSide;
  align?: AnchoredAlign;
  sideOffset?: number;
  variant?: MenuVariant;
  color?: ActionColor;
  rounded?: Rounded;
  shadow?: Shadow;
  contained?: boolean;
  disabled?: boolean;
  theme?: ThemeInput;
  open?: boolean;
  defaultOpen?: boolean;
  onOpenChange?: (open: boolean) => void;
  onSelect?: (selection: MenuSelection) => void;
  trigger?: ReactNode;
  "data-balsa"?: string;
  "data-palette"?: string;
}

export function DropdownMenu(rawProps: DropdownMenuProps) {
  const { props, theme } = useResolvedThemeProps("dropdown-menu", "overlays", rawProps, {
    variant: "surface",
    rounded: "lg",
    shadow: "auto",
  } as const);
  const {
    id,
    label,
    items,
    side = "bottom",
    align = "start",
    sideOffset = 8,
    variant,
    color = "primary",
    rounded,
    shadow,
    contained = false,
    disabled = false,
    theme: _themeInput,
    open,
    defaultOpen = false,
    onOpenChange,
    onSelect,
    trigger,
    "data-balsa": _dataBalsa,
    "data-palette": dataPalette,
    className,
    style,
    onKeyDown,
    ...domProps
  } = props;
  void _themeInput;
  void _dataBalsa;

  const [current, setOpen] = useControllableState({
    value: open,
    defaultValue: defaultOpen,
    onChange: onOpenChange,
  });
  const scope = useBalsaPortalScope();
  const rootRef = useRef<HTMLSpanElement | null>(null);
  const panelRef = useRef<HTMLDivElement | null>(null);
  const listRef = useRef<MenuListHandle | null>(null);
  const [mounted, setMounted] = useState(false);
  const [resolvedSide, setResolvedSide] = useState<AnchoredSide>(side);
  const [position, setPosition] = useState({ left: 0, top: 0, maxHeight: 0 });
  const [portalSnapshot, setPortalSnapshot] = useState<PortalPresentationSnapshot | null>(null);
  const themeRef = useRef(theme);
  themeRef.current = theme;
  const openRef = useRef(current);
  openRef.current = current;

  const showPanel = mounted && current;
  const portalHost = contained ? null : (scope?.host ?? (mounted ? document.body : null));

  function triggerElement(): HTMLButtonElement | null {
    return rootRef.current?.querySelector<HTMLButtonElement>(":scope > button") ?? null;
  }

  function close(restoreFocus = true): void {
    setOpen(false);
    if (restoreFocus) queueMicrotask(() => triggerElement()?.focus());
  }

  function capturePresentation(): void {
    const root = rootRef.current;
    if (!root?.isConnected) return;
    const currentTheme = themeRef.current;
    const presentation: ThemePresentation | undefined =
      currentTheme.inherited || currentTheme.explicitPresentation
        ? currentTheme.presentation
        : undefined;
    try {
      const snapshot = capturePortalPresentation(root, presentation);
      setPortalSnapshot((currentSnapshot) => (
        currentSnapshot
          && currentSnapshot.themeId === snapshot.themeId
          && currentSnapshot.themeBase === snapshot.themeBase
          && currentSnapshot.paletteId === snapshot.paletteId
          && currentSnapshot.adapt === snapshot.adapt
          ? currentSnapshot
          : snapshot
      ));
    } catch {
      setPortalSnapshot((currentSnapshot) => currentSnapshot);
    }
  }

  function updatePosition(): void {
    const triggerNode = triggerElement();
    const panelNode = panelRef.current;
    if (!triggerNode || !panelNode || !openRef.current) return;
    const next = getAnchoredLayerPosition(triggerNode, panelNode, {
      side,
      align,
      sideOffset,
      alignOffset: 0,
    });
    const rootRect = rootRef.current?.getBoundingClientRect();
    const left = next.left - (contained ? rootRect?.left ?? 0 : 0);
    const top = next.top - (contained ? rootRect?.top ?? 0 : 0);
    setPosition((currentPosition) => (
      currentPosition.left === left
        && currentPosition.top === top
        && currentPosition.maxHeight === next.maxHeight
        ? currentPosition
        : { left, top, maxHeight: next.maxHeight }
    ));
    setResolvedSide((currentSide) => currentSide === next.side ? currentSide : next.side);
  }

  function handleSelection(selection: MenuSelection): void {
    onSelect?.(selection);
    close();
  }

  function handleTriggerKeydown(event: KeyboardEvent<HTMLButtonElement>): void {
    if (["ArrowDown", "Enter", " "].includes(event.key)) {
      event.preventDefault();
      setOpen(true);
    } else if (event.key === "ArrowUp") {
      event.preventDefault();
      setOpen(true);
      queueMicrotask(() => {
        const buttons = panelRef.current?.querySelectorAll<HTMLElement>('[role^="menuitem"]');
        buttons?.item(buttons.length - 1)?.focus();
      });
    }
    onKeyDown?.(event as KeyboardEvent<HTMLElement>);
  }

  useLayoutEffect(() => {
    setMounted(true);
  }, []);

  useLayoutEffect(() => {
    if (!showPanel) return;
    capturePresentation();
    updatePosition();
    listRef.current?.focusFirst();
  }, [showPanel, side, align, sideOffset, contained]);

  useLayoutEffect(() => {
    if (!mounted) return;

    function handleDocumentPointer(event: PointerEvent): void {
      if (!openRef.current) return;
      const target = event.target as Node;
      if (rootRef.current?.contains(target) || panelRef.current?.contains(target)) return;
      close(false);
    }

    document.addEventListener("pointerdown", handleDocumentPointer, true);
    window.addEventListener("resize", updatePosition, { passive: true });
    window.addEventListener("scroll", updatePosition, true);
    return () => {
      document.removeEventListener("pointerdown", handleDocumentPointer, true);
      window.removeEventListener("resize", updatePosition);
      window.removeEventListener("scroll", updatePosition, true);
    };
  }, [mounted, contained, side, align, sideOffset]);

  const panelPresentation = portalSnapshot ?? {
    themeId: theme.presentation.id,
    themeBase: theme.presentation.base,
    paletteId: dataPalette,
    style: Object.fromEntries(
      Object.entries(theme.presentation.style).filter(([property]) => property.startsWith("--balsa-")),
    ) as PortalPresentationSnapshot["style"],
  };
  const triggerClasses = mergeClasses(
    "border-balsa-border-strong bg-balsa-surface px-balsa-md py-balsa-2xs text-balsa-surface-foreground hover:bg-balsa-muted",
    rawProps.rounded === undefined ? "rounded-balsa-control" : roundedClasses[rounded],
    className,
  );
  const panelStyle = {
    left: `${position.left}px`,
    top: `${position.top}px`,
    maxHeight: `${position.maxHeight}px`,
    ...panelPresentation.style,
  } as CSSProperties;
  const panel = showPanel ? (
    <div
      ref={panelRef}
      data-balsa="dropdown-menu-panel"
      data-theme={panelPresentation.themeId}
      data-theme-base={panelPresentation.themeBase}
      data-palette={dataPalette ?? panelPresentation.paletteId}
      data-side={resolvedSide}
      data-shadow={shadow}
      className={mergeClasses("z-[65]", contained ? "absolute" : "fixed")}
      style={panelStyle}
    >
      <MenuList
        id={id}
        ref={listRef}
        label={label}
        items={items}
        variant={variant}
        color={color}
        rounded={rounded}
        shadow={shadow}
        data-palette={dataPalette ?? panelPresentation.paletteId}
        onSelect={handleSelection}
        onDismiss={() => close()}
      />
    </div>
  ) : null;

  return (
    <BalsaThemeContext.Provider value={theme}>
      <span
        {...domProps}
        ref={rootRef}
        data-balsa="dropdown-menu"
        data-theme={theme.explicitPresentation?.id}
        data-theme-base={theme.explicitPresentation?.base}
        data-palette={dataPalette}
        data-color={color}
        data-rounded={rounded}
        data-state={current ? "open" : "closed"}
        className="relative inline-flex"
        style={{
          ...theme.explicitPresentation?.style,
          ...style,
        } as CSSProperties}
      >
        <Button
          id={`${id}-trigger`}
          variant="outline"
          color="neutral"
          size="md"
          disabled={disabled}
          aria-expanded={current}
          aria-controls={id}
          aria-haspopup="menu"
          className={triggerClasses}
          onClick={() => {
            if (!disabled) setOpen(!current);
          }}
          onKeyDown={handleTriggerKeydown}
        >
          {trigger ?? "Open menu"}
        </Button>
        {contained ? panel : (portalHost && panel ? createPortal(panel, portalHost) : null)}
      </span>
    </BalsaThemeContext.Provider>
  );
}
