// src/components/ui/Kbd.vue
<script setup lang="ts">
import { computed, useAttrs } from "vue";
import { mergeClasses, withoutClassAttribute } from "./classes";
import { roundedClasses, type Rounded } from "./form";
import type { Shadow, ThemeInput } from "./theme";
import { useResolvedThemeProps } from "./theme-context";

export type KbdVariant = "raised" | "outline" | "soft";
export type KbdSize = "sm" | "md" | "lg";

defineOptions({ inheritAttrs: false });

const rawProps = withDefaults(
  defineProps<{
    keys?: readonly string[];
    separator?: string;
    variant?: KbdVariant;
    size?: KbdSize;
    rounded?: Rounded;
    shadow?: Shadow;
    accessibleLabel?: string;
    theme?: ThemeInput;
  }>(),
  {
    keys: () => [],
    separator: "+",
  },
);
const { props, theme } = useResolvedThemeProps(
  "kbd",
  "controls",
  rawProps,
  { variant: "soft", size: "md", rounded: "md", shadow: "auto" } as const,
);

const attrs = useAttrs();
const hasKeys = computed(() => props.keys.length > 0);
const rootAttrs = computed(() => withoutClassAttribute(attrs));

const variantClasses: Readonly<Record<KbdVariant, string[]>> = {
  raised: [
    "border-balsa-border-strong",
    "bg-balsa-surface-elevated",
    "text-balsa-surface-elevated-foreground",
  ],
  outline: ["border-balsa-border-strong", "bg-transparent", "text-balsa-foreground"],
  soft: ["border-transparent", "bg-balsa-muted", "text-balsa-muted-foreground"],
};
const sizeClasses: Readonly<Record<KbdSize, string[]>> = {
  sm: ["min-h-5", "min-w-5", "px-1.5", "text-[0.6875rem]"],
  md: ["min-h-6", "min-w-6", "px-2", "text-xs"],
  lg: ["min-h-8", "min-w-8", "px-2.5", "text-sm"],
};
const groupGapClasses: Readonly<Record<KbdSize, string>> = {
  sm: "gap-1",
  md: "gap-1.5",
  lg: "gap-2",
};

const capClasses = computed(() =>
  mergeClasses(
    "inline-flex shrink-0 select-none items-center justify-center border font-mono font-medium leading-none whitespace-nowrap",
    variantClasses[props.variant],
    sizeClasses[props.size],
    roundedClasses[props.rounded],
  ),
);
const classes = computed(() =>
  mergeClasses(
    "align-middle font-mono",
    hasKeys.value
      ? ["inline-flex items-center whitespace-nowrap", groupGapClasses[props.size]]
      : capClasses.value,
    attrs.class,
  ),
);
</script>

<template>
  <kbd
    v-bind="rootAttrs"
    data-balsa="kbd"
    :data-theme="theme.explicitPresentation.value?.id"
    :data-theme-base="theme.explicitPresentation.value?.base"
    :data-variant="props.variant"
    :data-size="props.size"
    :data-rounded="props.rounded"
    :data-shadow="props.shadow"
    :data-group="hasKeys"
    :aria-label="props.accessibleLabel"
    :class="classes"
    :style="[attrs.style, theme.explicitPresentation.value?.style]"
  >
    <template v-if="hasKeys">
      <template v-for="(key, index) in props.keys" :key="`${key}-${index}`">
        <span data-balsa="kbd-key" :class="capClasses">{{ key }}</span>
        <span
          v-if="index < props.keys.length - 1"
          data-balsa="kbd-separator"
          class="text-balsa-muted-foreground"
          aria-hidden="true"
        >
          {{ props.separator }}
        </span>
      </template>
    </template>
    <slot v-else />
  </kbd>
</template>

// packages/react/src/components/ui/Kbd.tsx
import { Fragment, type CSSProperties, type HTMLAttributes, type ReactNode } from "react";
import { mergeClasses } from "./classes";
import { roundedClasses, type Rounded } from "./form";
import {
  BalsaThemeContext,
  useResolvedThemeProps,
} from "./theme-context";
import type { Shadow, ThemeInput } from "./theme";

export type KbdVariant = "raised" | "outline" | "soft";
export type KbdSize = "sm" | "md" | "lg";

export interface KbdProps extends HTMLAttributes<HTMLElement> {
  keys?: readonly string[];
  separator?: string;
  variant?: KbdVariant;
  size?: KbdSize;
  rounded?: Rounded;
  shadow?: Shadow;
  accessibleLabel?: string;
  theme?: ThemeInput;
  children?: ReactNode;
}

const variantClasses: Readonly<Record<KbdVariant, string[]>> = {
  raised: [
    "border-balsa-border-strong",
    "bg-balsa-surface-elevated",
    "text-balsa-surface-elevated-foreground",
  ],
  outline: ["border-balsa-border-strong", "bg-transparent", "text-balsa-foreground"],
  soft: ["border-transparent", "bg-balsa-muted", "text-balsa-muted-foreground"],
};
const sizeClasses: Readonly<Record<KbdSize, string[]>> = {
  sm: ["min-h-5", "min-w-5", "px-balsa-2xs", "text-[0.6875rem]"],
  md: ["min-h-6", "min-w-6", "px-balsa-xs", "text-xs"],
  lg: ["min-h-8", "min-w-8", "px-balsa-sm", "text-sm"],
};
const groupGapClasses: Readonly<Record<KbdSize, string>> = {
  sm: "gap-balsa-3xs",
  md: "gap-balsa-2xs",
  lg: "gap-balsa-xs",
};

export function Kbd(rawProps: KbdProps) {
  const { props, theme } = useResolvedThemeProps("kbd", "controls", rawProps, {
    variant: "soft",
    size: "md",
    rounded: "md",
    shadow: "auto",
  } as const);
  const {
    keys = [],
    separator = "+",
    variant,
    size,
    rounded,
    shadow,
    accessibleLabel,
    theme: _themeInput,
    className,
    style,
    children,
    ...domProps
  } = props;
  void _themeInput;

  const hasKeys = keys.length > 0;
  const capClasses = mergeClasses(
    "inline-flex shrink-0 select-none items-center justify-center font-mono font-medium leading-none whitespace-nowrap",
    variantClasses[variant],
    sizeClasses[size],
    roundedClasses[rounded],
  );
  const classes = mergeClasses(
    "align-middle font-mono",
    hasKeys
      ? ["inline-flex items-center whitespace-nowrap", groupGapClasses[size]]
      : capClasses,
    className,
  );

  return (
    <BalsaThemeContext.Provider value={theme}>
      <kbd
        {...domProps}
        data-balsa="kbd"
        data-theme={theme.explicitPresentation?.id}
        data-theme-base={theme.explicitPresentation?.base}
        data-variant={variant}
        data-size={size}
        data-rounded={rounded}
        data-shadow={shadow}
        data-group={hasKeys}
        aria-label={accessibleLabel}
        className={classes}
        style={
          {
            ...theme.explicitPresentation?.style,
            ...style,
          } as CSSProperties
        }
      >
        {hasKeys
          ? keys.map((key, index) => (
            <Fragment key={`${key}-${index}`}>
              <span data-balsa="kbd-key" className={capClasses}>{key}</span>
              {index < keys.length - 1 ? (
                <span
                  data-balsa="kbd-separator"
                  className="text-balsa-muted-foreground"
                  aria-hidden="true"
                >
                  {separator}
                </span>
              ) : null}
            </Fragment>
          ))
          : children}
      </kbd>
    </BalsaThemeContext.Provider>
  );
}
