// src/components/ui/Charts.vue
<script setup lang="ts">
import { computed } from "vue";
import { VisArea, VisAreaSelectors, VisAxis, VisDonut, VisDonutSelectors, VisGroupedBar, VisGroupedBarSelectors, VisLine, VisLineSelectors, VisSingleContainer, VisStackedBar, VisStackedBarSelectors, VisTooltip, VisXYContainer } from "@unovis/vue";
import { CurveType } from "@unovis/ts";
import ChartContainer from "./ChartContainer.vue";
import ChartCrosshair from "./ChartCrosshair.vue";
import ChartLegendContent from "./ChartLegendContent.vue";
import type { ChartConfig, ChartPaletteRole, ChartTableSeries } from "./chart";
import type { IconComponent } from "./Icon.vue";
import type { Rounded } from "./form";
import type { SemanticColor } from "./types";
import type { ThemeInput } from "./theme";

export type ChartsType = "line" | "area" | "bar" | "donut" | "doughnut";
export type ChartsBarMode = "grouped" | "stacked";
export interface ChartSeries {
  key?: string;
  label: string;
  data: readonly number[];
  color?: SemanticColor | "neutral";
  icon?: IconComponent;
}

interface XYDatum {
  index: number;
  label: string;
  values: number[];
}

interface DonutDatum {
  key: string;
  label: string;
  value: number;
  color: string;
}

const props = withDefaults(defineProps<{
  title: string;
  description?: string;
  type?: ChartsType;
  labels: readonly string[];
  series: readonly ChartSeries[];
  colors?: readonly SemanticColor[];
  config?: ChartConfig;
  barMode?: ChartsBarMode;
  loading?: boolean;
  error?: string;
  emptyText?: string;
  showGrid?: boolean;
  showXAxis?: boolean;
  showYAxis?: boolean;
  showTooltip?: boolean;
  showLegend?: boolean;
  showCaption?: boolean;
  showTable?: boolean;
  responsive?: boolean;
  width?: number;
  height?: number;
  rounded?: Rounded;
  labelFormatter?: (label: string, index: number) => string;
  valueFormatter?: (value: number, series: ChartSeries, index: number) => string;
  theme?: ThemeInput;
}>(), {
  type: "bar",
  barMode: "grouped",
  loading: false,
  emptyText: "No chart data.",
  showGrid: true,
  showXAxis: true,
  showYAxis: true,
  showTooltip: true,
  showLegend: true,
  showCaption: true,
  showTable: false,
  responsive: true,
  height: 260,
  labelFormatter: (label: string) => label,
  valueFormatter: (value: number) => new Intl.NumberFormat().format(value),
});

const defaultRoles: readonly ChartPaletteRole[] = ["primary", "secondary", "accent", "neutral"];
const normalizedType = computed(() => props.type === "doughnut" ? "donut" : props.type);
const seriesKeys = computed(() => props.series.map((series, index) => series.key ?? `series-${index}`));
const config = computed<ChartConfig>(() => {
  if (props.config) return props.config;
  if (normalizedType.value === "donut") {
    return Object.fromEntries(props.labels.map((label, index) => [
      `segment-${index}`,
      {
        label: props.labelFormatter(label, index),
        color: props.series[0]?.color ?? props.colors?.[index % (props.colors.length || 1)] ?? defaultRoles[index % defaultRoles.length],
        icon: props.series[0]?.icon,
      },
    ]));
  }
  return Object.fromEntries(props.series.map((series, index) => [
    seriesKeys.value[index]!,
    {
      label: series.label,
      color: series.color ?? props.colors?.[index % (props.colors.length || 1)] ?? defaultRoles[index % defaultRoles.length],
      icon: series.icon,
    },
  ]));
});
const tableSeries = computed<ChartTableSeries[]>(() => props.series.map((series, index) => ({ key: seriesKeys.value[index]!, label: series.label, data: series.data })));
const empty = computed(() => !props.series.length || !props.labels.length || props.series.every((series) => !series.data.length));
const xyData = computed<XYDatum[]>(() => props.labels.map((label, index) => ({
  index,
  label,
  values: props.series.map((series) => series.data[index] ?? 0),
})));
const x = (datum: XYDatum) => datum.index;
const y = computed(() => props.series.map((_, seriesIndex) => (datum: XYDatum) => datum.values[seriesIndex] ?? 0));
const labelTick = (tick: number | Date) => {
  const index = typeof tick === "number" ? Math.round(tick) : 0;
  return props.labelFormatter(props.labels[index] ?? "", index);
};
const valueTick = (tick: number | Date) => props.valueFormatter(Number(tick), props.series[0] ?? { label: "Value", data: [] }, 0);
const tableValueFormatter = (value: number, series: ChartTableSeries, index: number) => props.valueFormatter(
  value,
  props.series.find((item, seriesIndex) => (item.key ?? `series-${seriesIndex}`) === series.key) ?? { label: series.label, data: series.data },
  index,
);
const cornerRadius = computed(() => ({ none: 0, sm: 2, md: 4, lg: 6, xl: 8, "2xl": 12, "3xl": 16, full: 9999 } satisfies Record<Rounded, number>)[props.rounded ?? "lg"]);

function escapeHtml(value: string): string {
  return value.replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;");
}

function tooltipTemplate(colors: Readonly<Record<string, string>>, datum: XYDatum): string {
  const rows = props.series.map((series, index) => `<div class="balsa-chart-tooltip-row"><span class="balsa-chart-tooltip-marker" style="background:${escapeHtml(colors[seriesKeys.value[index]!] ?? "currentColor")}"></span><span>${escapeHtml(series.label)}</span><strong>${escapeHtml(props.valueFormatter(datum.values[index] ?? 0, series, datum.index))}</strong></div>`).join("");
  return `<div class="balsa-chart-tooltip-content"><div class="balsa-chart-tooltip-label">${escapeHtml(props.labelFormatter(datum.label, datum.index))}</div>${rows}</div>`;
}

function colorsArray(colors: Readonly<Record<string, string>>): string[] {
  return seriesKeys.value.map((key) => colors[key] ?? "currentColor");
}
function dashArray(_: XYDatum[], index: number): number[] {
  return index % 3 === 1 ? [7, 4] : index % 3 === 2 ? [2, 4] : [];
}
function areaDefs(colors: Readonly<Record<string, string>>): string {
  return seriesKeys.value.map((key, index) => `<linearGradient id="balsa-area-${index}" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stop-color="${escapeHtml(colors[key] ?? "currentColor")}" stop-opacity="0.28"/><stop offset="100%" stop-color="${escapeHtml(colors[key] ?? "currentColor")}" stop-opacity="0.03"/></linearGradient>`).join("");
}
function donutData(colors: Readonly<Record<string, string>>): DonutDatum[] {
  const source = props.series[0];
  return props.labels.map((label, index) => ({
    key: `segment-${index}`,
    label,
    value: source?.data[index] ?? 0,
    color: colors[`segment-${index}`] ?? "currentColor",
  }));
}
function donutTooltip(datum: DonutDatum): string {
  const source = props.series[0] ?? { label: "Value", data: [] };
  return `<div class="balsa-chart-tooltip-content"><div class="balsa-chart-tooltip-row"><span class="balsa-chart-tooltip-marker" style="background:${escapeHtml(datum.color)}"></span><span>${escapeHtml(datum.label)}</span><strong>${escapeHtml(props.valueFormatter(datum.value, source, props.labels.indexOf(datum.label)))}</strong></div></div>`;
}
</script>

<template>
  <ChartContainer
    data-balsa="charts"
    :title="props.title"
    :description="props.description"
    :config="config"
    :labels="props.labels"
    :table-series="tableSeries"
    :loading="props.loading"
    :error="props.error"
    :empty="empty"
    :empty-text="props.emptyText"
    :show-caption="props.showCaption"
    :show-table="props.showTable"
    :label-formatter="props.labelFormatter"
    :value-formatter="tableValueFormatter"
    :responsive="props.responsive"
    :width="props.width"
    :height="props.height"
    :rounded="props.rounded"
    :theme="props.theme"
    :data-type="normalizedType"
    :data-bar-mode="props.barMode"
  >
    <template #default="slotProps">
      <VisSingleContainer
        v-if="normalizedType === 'donut'"
        :data="donutData(slotProps.colors)"
        :width="slotProps.width"
        :height="slotProps.height"
        :duration="slotProps.reducedMotion ? 0 : undefined"
        :aria-label="props.title"
        class="balsa-chart-plot"
      >
        <VisDonut
          :value="(datum: DonutDatum) => datum.value"
          :color="(datum: DonutDatum) => datum.color"
          :pad-angle="0.025"
          :corner-radius="Math.min(cornerRadius, 8)"
          :arc-width="28"
        />
        <VisTooltip v-if="props.showTooltip" :triggers="{ [VisDonutSelectors.segment]: donutTooltip }" class-name="balsa-chart-tooltip" />
      </VisSingleContainer>
      <VisXYContainer
        v-else
        :data="xyData"
        :width="slotProps.width"
        :height="slotProps.height"
        :duration="slotProps.reducedMotion ? 0 : undefined"
        :svg-defs="normalizedType === 'area' ? areaDefs(slotProps.colors) : undefined"
        :y-domain="[0, undefined]"
        :aria-label="props.title"
        class="balsa-chart-plot"
      >
        <VisLine
          v-if="normalizedType === 'line'"
          :x="x"
          :y="y"
          :color="colorsArray(slotProps.colors)"
          :line-width="2"
          :curve-type="CurveType.MonotoneX"
          :line-dash-array="dashArray"
          highlight-on-hover
        />
        <VisArea
          v-else-if="normalizedType === 'area'"
          :x="x"
          :y="y"
          :color="seriesKeys.map((_, index) => `url(#balsa-area-${index})`)"
          :line-color="colorsArray(slotProps.colors)"
          :line-dash-array="dashArray"
          :line-width="2"
          :curve-type="CurveType.MonotoneX"
          line
        />
        <VisGroupedBar
          v-else-if="props.barMode === 'grouped'"
          :x="x"
          :y="y"
          :color="colorsArray(slotProps.colors)"
          :group-padding="0.18"
          :bar-padding="0.08"
          :rounded-corners="cornerRadius"
        />
        <VisStackedBar
          v-else
          :x="x"
          :y="y"
          :color="colorsArray(slotProps.colors)"
          :bar-padding="0.22"
          :rounded-corners="cornerRadius"
        />
        <VisAxis v-if="props.showXAxis" type="x" :grid-line="false" :domain-line="false" :tick-line="false" :tick-format="labelTick" :num-ticks="props.labels.length" />
        <VisAxis v-if="props.showYAxis" type="y" :grid-line="props.showGrid" :domain-line="false" :tick-line="false" :tick-format="valueTick" />
        <ChartCrosshair v-if="props.showTooltip" :x="x" :y="y" :template="(datum: XYDatum) => tooltipTemplate(slotProps.colors, datum)" />
        <VisTooltip
          v-if="props.showTooltip"
          :triggers="{
          [VisLineSelectors.line]: (datum: XYDatum) => tooltipTemplate(slotProps.colors, datum),
          [VisAreaSelectors.area]: (datum: XYDatum) => tooltipTemplate(slotProps.colors, datum),
          [VisGroupedBarSelectors.bar]: (datum: XYDatum) => tooltipTemplate(slotProps.colors, datum),
          [VisStackedBarSelectors.bar]: (datum: XYDatum) => tooltipTemplate(slotProps.colors, datum),
        }" class-name="balsa-chart-tooltip" />
      </VisXYContainer>
      <div v-if="normalizedType === 'donut' && $slots.center" class="pointer-events-none absolute inset-0 grid place-items-center">
        <slot name="center" />
      </div>
      <ChartLegendContent v-if="props.showLegend" class="mt-3" />
    </template>
  </ChartContainer>
</template>

// registry/react/components/charts/Charts.tsx
import {
  VisArea,
  VisAreaSelectors,
  VisAxis,
  VisDonut,
  VisDonutSelectors,
  VisGroupedBar,
  VisGroupedBarSelectors,
  VisLine,
  VisLineSelectors,
  VisSingleContainer,
  VisStackedBar,
  VisStackedBarSelectors,
  VisTooltip,
  VisXYContainer,
} from "@unovis/react";
import { CurveType } from "@unovis/ts";
import { type HTMLAttributes, type ReactNode, useMemo } from "react";
import { ChartContainer } from "./ChartContainer";
import { ChartCrosshair } from "./ChartCrosshair";
import { ChartLegendContent } from "./ChartLegendContent";
import type { ChartConfig, ChartPaletteRole, ChartTableSeries } from "./chart";
import type { Rounded } from "./form";
import type { IconComponent } from "./Icon";
import type { ThemeInput } from "./theme";
import type { SemanticColor } from "./types";

export type ChartsType = "line" | "area" | "bar" | "donut" | "doughnut";
export type ChartsBarMode = "grouped" | "stacked";
export type ChartsAreaFill = "gradient" | "solid" | "none";

export interface ChartSeries {
  key?: string;
  label: string;
  data: readonly number[];
  color?: SemanticColor | "neutral";
  icon?: IconComponent;
}

interface XYDatum {
  index: number;
  label: string;
  values: number[];
}

interface DonutDatum {
  key: string;
  label: string;
  value: number;
  color: string;
}

export interface ChartsProps extends Omit<HTMLAttributes<HTMLElement>, "title" | "children"> {
  title: string;
  description?: string;
  type?: ChartsType;
  labels: readonly string[];
  series: readonly ChartSeries[];
  colors?: readonly SemanticColor[];
  config?: ChartConfig;
  barMode?: ChartsBarMode;
  loading?: boolean;
  error?: string;
  emptyText?: string;
  showGrid?: boolean;
  showXAxis?: boolean;
  showYAxis?: boolean;
  showTooltip?: boolean;
  showLegend?: boolean;
  showCaption?: boolean;
  showTable?: boolean;
  responsive?: boolean;
  areaFill?: ChartsAreaFill;
  width?: number;
  height?: number;
  rounded?: Rounded;
  labelFormatter?: (label: string, index: number) => string;
  valueFormatter?: (value: number, series: ChartSeries, index: number) => string;
  theme?: ThemeInput;
  center?: ReactNode;
}

const defaultRoles: readonly ChartPaletteRole[] = ["primary", "secondary", "accent", "neutral"];
const areaFillOpacity: Readonly<Record<ChartsAreaFill, readonly [number, number]>> = {
  gradient: [0.5, 0.02],
  solid: [0.24, 0.24],
  none: [0, 0],
};
const plotStyle = ".balsa-chart-plot{display:block;position:relative;width:100%}";

const x = (datum: XYDatum) => datum.index;

function escapeHtml(value: string): string {
  return value.replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;");
}

function dashArray(_: XYDatum[], index: number): number[] {
  return index % 3 === 1 ? [7, 4] : index % 3 === 2 ? [2, 4] : [];
}

export function Charts({
  title,
  description,
  type = "bar",
  labels,
  series,
  colors,
  config: explicitConfig,
  barMode = "grouped",
  loading = false,
  error,
  emptyText = "No chart data.",
  showGrid = true,
  showXAxis = true,
  showYAxis = true,
  showTooltip = true,
  showLegend = true,
  showCaption = true,
  showTable = false,
  responsive = true,
  areaFill = "gradient",
  width,
  height = 260,
  rounded,
  labelFormatter = (label: string) => label,
  valueFormatter = (value: number) => new Intl.NumberFormat().format(value),
  theme,
  center,
  ...domProps
}: ChartsProps) {
  const normalizedType = type === "doughnut" ? "donut" : type;
  const seriesKeys = series.map((item, index) => item.key ?? `series-${index}`);
  const empty = !series.length || !labels.length || series.every((item) => !item.data.length);
  const xyData = labels.map((label, index) => ({
    index,
    label,
    values: series.map((item) => item.data[index] ?? 0),
  }));
  const y = series.map((_, seriesIndex) => (datum: XYDatum) => datum.values[seriesIndex] ?? 0);
  const cornerRadius = ({ none: 0, sm: 2, md: 4, lg: 6, xl: 8, "2xl": 12, "3xl": 16, full: 9999 } satisfies Record<Rounded, number>)[rounded ?? "lg"];
  const config = useMemo<ChartConfig>(() => {
    if (explicitConfig) return explicitConfig;
    if (normalizedType === "donut") {
      return Object.fromEntries(labels.map((label, index) => [
        `segment-${index}`,
        {
          label: labelFormatter(label, index),
          color: series[0]?.color ?? colors?.[index % (colors.length || 1)] ?? defaultRoles[index % defaultRoles.length]!,
          icon: series[0]?.icon,
        },
      ]));
    }
    return Object.fromEntries(series.map((item, index) => [
      seriesKeys[index]!,
      {
        label: item.label,
        color: item.color ?? colors?.[index % (colors.length || 1)] ?? defaultRoles[index % defaultRoles.length]!,
        icon: item.icon,
      },
    ]));
  }, [colors, explicitConfig, labelFormatter, labels, normalizedType, series, seriesKeys]);
  const tableSeries: ChartTableSeries[] = series.map((item, index) => ({
    key: seriesKeys[index]!,
    label: item.label,
    data: item.data,
  }));

  function labelTick(tick: number | Date): string {
    const index = typeof tick === "number" ? Math.round(tick) : 0;
    return labelFormatter(labels[index] ?? "", index);
  }

  function valueTick(tick: number | Date): string {
    return valueFormatter(Number(tick), series[0] ?? { label: "Value", data: [] }, 0);
  }

  function tableValueFormatter(value: number, tableItem: ChartTableSeries, index: number): string {
    return valueFormatter(
      value,
      series.find((item, seriesIndex) => (item.key ?? `series-${seriesIndex}`) === tableItem.key)
        ?? { label: tableItem.label, data: tableItem.data },
      index,
    );
  }

  function tooltipTemplate(resolvedColors: Readonly<Record<string, string>>, datum: XYDatum): string {
    const rows = series.map((item, index) => `<div class="balsa-chart-tooltip-row"><span class="balsa-chart-tooltip-marker" style="background:${escapeHtml(resolvedColors[seriesKeys[index]!] ?? "currentColor")}"></span><span>${escapeHtml(item.label)}</span><strong>${escapeHtml(valueFormatter(datum.values[index] ?? 0, item, datum.index))}</strong></div>`).join("");
    return `<div class="balsa-chart-tooltip-content"><div class="balsa-chart-tooltip-label">${escapeHtml(labelFormatter(datum.label, datum.index))}</div>${rows}</div>`;
  }

  function colorsArray(resolvedColors: Readonly<Record<string, string>>): string[] {
    return seriesKeys.map((key) => resolvedColors[key] ?? "currentColor");
  }

  function areaDefs(resolvedColors: Readonly<Record<string, string>>): string {
    const [top, bottom] = areaFillOpacity[areaFill];
    return seriesKeys.map((key, index) => {
      const color = escapeHtml(resolvedColors[key] ?? "currentColor");
      return `<linearGradient id="balsa-area-${index}" x1="0" x2="0" y1="0" y2="1">`
        + `<stop offset="0%" stop-color="${color}" stop-opacity="${top}"/>`
        + `<stop offset="100%" stop-color="${color}" stop-opacity="${bottom}"/>`
        + `</linearGradient>`;
    }).join("");
  }

  function donutData(resolvedColors: Readonly<Record<string, string>>): DonutDatum[] {
    const source = series[0];
    return labels.map((label, index) => ({
      key: `segment-${index}`,
      label,
      value: source?.data[index] ?? 0,
      color: resolvedColors[`segment-${index}`] ?? "currentColor",
    }));
  }

  function donutTooltip(datum: DonutDatum): string {
    const source = series[0] ?? { label: "Value", data: [] };
    return `<div class="balsa-chart-tooltip-content"><div class="balsa-chart-tooltip-row"><span class="balsa-chart-tooltip-marker" style="background:${escapeHtml(datum.color)}"></span><span>${escapeHtml(datum.label)}</span><strong>${escapeHtml(valueFormatter(datum.value, source, labels.indexOf(datum.label)))}</strong></div></div>`;
  }

  return (
    <>
      <style>{plotStyle}</style>
      <ChartContainer
        {...domProps}
        data-balsa="charts"
        data-type={normalizedType}
        data-bar-mode={barMode}
        title={title}
        description={description}
        config={config}
        labels={labels}
        tableSeries={tableSeries}
        loading={loading}
        error={error}
        empty={empty}
        emptyText={emptyText}
        showCaption={showCaption}
        showTable={showTable}
        labelFormatter={labelFormatter}
        valueFormatter={tableValueFormatter}
        responsive={responsive}
        width={width}
        height={height}
        rounded={rounded}
        theme={theme}
      >
        {(slotProps) => (
          <>
            {normalizedType === "donut" ? (
              <VisSingleContainer
                data={donutData(slotProps.colors)}
                width={slotProps.width}
                height={slotProps.height}
                duration={slotProps.reducedMotion ? 0 : undefined}
                className="balsa-chart-plot"
              >
                <VisDonut
                  value={(datum: DonutDatum) => datum.value}
                  color={(datum: DonutDatum) => datum.color}
                  padAngle={0.025}
                  cornerRadius={Math.min(cornerRadius, 8)}
                  arcWidth={28}
                />
                {showTooltip ? (
                  <VisTooltip
                    triggers={{ [VisDonutSelectors.segment]: donutTooltip }}
                    className="balsa-chart-tooltip"
                  />
                ) : null}
              </VisSingleContainer>
            ) : (
              <VisXYContainer
                data={xyData}
                width={slotProps.width}
                height={slotProps.height}
                duration={slotProps.reducedMotion ? 0 : undefined}
                svgDefs={normalizedType === "area" ? areaDefs(slotProps.colors) : undefined}
                yDomain={[0, undefined]}
                className="balsa-chart-plot"
              >
                {normalizedType === "line" ? (
                  <VisLine
                    x={x}
                    y={y}
                    color={colorsArray(slotProps.colors)}
                    lineWidth={2}
                    curveType={CurveType.MonotoneX}
                    lineDashArray={dashArray}
                    highlightOnHover
                  />
                ) : null}
                {normalizedType === "area" ? (
                  <VisArea
                    x={x}
                    y={y}
                    color={seriesKeys.map((_, index) => `url(#balsa-area-${index})`)}
                    lineColor={colorsArray(slotProps.colors)}
                    lineDashArray={dashArray}
                    lineWidth={2}
                    curveType={CurveType.MonotoneX}
                    line
                  />
                ) : null}
                {normalizedType === "bar" && barMode === "grouped" ? (
                  <VisGroupedBar
                    x={x}
                    y={y}
                    color={colorsArray(slotProps.colors)}
                    groupPadding={0.18}
                    barPadding={0.08}
                    roundedCorners={cornerRadius}
                  />
                ) : null}
                {normalizedType === "bar" && barMode === "stacked" ? (
                  <VisStackedBar
                    x={x}
                    y={y}
                    color={colorsArray(slotProps.colors)}
                    barPadding={0.22}
                    roundedCorners={cornerRadius}
                  />
                ) : null}
                {showXAxis ? (
                  <VisAxis type="x" gridLine={false} domainLine={false} tickLine={false} tickFormat={labelTick} numTicks={labels.length} />
                ) : null}
                {showYAxis ? (
                  <VisAxis type="y" gridLine={showGrid} domainLine={false} tickLine={false} tickFormat={valueTick} />
                ) : null}
                {showTooltip ? (
                  <ChartCrosshair x={x} y={y} template={(datum: XYDatum) => tooltipTemplate(slotProps.colors, datum)} />
                ) : null}
                {showTooltip ? (
                  <VisTooltip
                    triggers={{
                      [VisLineSelectors.line]: (datum: XYDatum) => tooltipTemplate(slotProps.colors, datum),
                      [VisAreaSelectors.area]: (datum: XYDatum) => tooltipTemplate(slotProps.colors, datum),
                      [VisGroupedBarSelectors.bar]: (datum: XYDatum) => tooltipTemplate(slotProps.colors, datum),
                      [VisStackedBarSelectors.bar]: (datum: XYDatum) => tooltipTemplate(slotProps.colors, datum),
                    }}
                    className="balsa-chart-tooltip"
                  />
                ) : null}
              </VisXYContainer>
            )}
            {normalizedType === "donut" && center ? (
              <div className="pointer-events-none absolute inset-0 grid place-items-center">
                {center}
              </div>
            ) : null}
            {showLegend ? <ChartLegendContent className="mt-balsa-md" /> : null}
          </>
        )}
      </ChartContainer>
    </>
  );
}
