// packages/react/src/components/ui/ChartTooltip.tsx
import { VisTooltip } from "@unovis/react";
import type { TooltipConfigInterface } from "@unovis/ts";

export type ChartTooltipProps = Pick<
  TooltipConfigInterface,
  "triggers" | "followCursor" | "allowHover" | "showDelay" | "hideDelay"
>;

export function ChartTooltip(props: ChartTooltipProps) {
  return <VisTooltip {...props} className="balsa-chart-tooltip" />;
}

// src/components/ui/ChartTooltip.vue
<script setup lang="ts">
import { VisTooltip } from "@unovis/vue";
import type { TooltipConfigInterface } from "@unovis/ts";

defineProps<Pick<TooltipConfigInterface, "triggers" | "followCursor" | "allowHover" | "showDelay" | "hideDelay">>();
</script>

<template>
  <VisTooltip v-bind="$props" class-name="balsa-chart-tooltip" />
</template>
