// packages/react/src/components/ui/Text3D.tsx
import {
  forwardRef,
  useImperativeHandle,
  useLayoutEffect,
  useMemo,
  useRef,
  useState,
  type CSSProperties,
  type HTMLAttributes,
} from "react";
import type { Font } from "three/examples/jsm/loaders/FontLoader.js";
import { mergeClasses } from "./classes";
import { GradientBackground, type GradientBackgroundHandle } from "./GradientBackground";
import {
  gradientBackgroundPatternDefaults,
} from "./gradient-background";
import {
  TEXT_3D_DEFAULTS,
  buildText3DFallbackStyle,
  hasText3DPalette,
  matchText3DFont,
  resolveText3DConfig,
  resolveText3DPaletteColors,
  resolveText3DPaletteEnvironment,
  resolveText3DThemeFontFamily,
  text3DGradientColors,
  usesText3DCustomFontFamily,
  type BalsaText3DConfig,
  type Text3DAlignment,
  type Text3DCaptureOptions,
  type Text3DColorMode,
  type Text3DColors,
  type Text3DConfigInput,
  type Text3DDirectOverrides,
  type Text3DEnvironment,
  type Text3DExposed,
  type Text3DFont,
  type Text3DFontMode,
  type Text3DFontWeight,
  type Text3DMaterial,
  type Text3DPose,
  type Text3DPoseMode,
  type Text3DPresetName,
  type Text3DQuality,
  type Text3DWheelZoom,
} from "./text-3d";
import { loadText3DFont, loadText3DRemoteFont } from "./text-3d-fonts";
import {
  Text3DRenderer,
  text3DGeometrySignature,
  type Text3DEnvironmentColors,
} from "./text-3d-renderer";
import type { ThemeInput } from "./theme";

export type Text3DHandle = Text3DExposed;

export interface Text3DProps extends Omit<HTMLAttributes<HTMLDivElement>, "children"> {
  "data-balsa"?: string;
  preset?: Text3DPresetName;
  config?: Text3DConfigInput;
  overrides?: Text3DDirectOverrides;
  seed?: number;
  text?: string;
  fontMode?: Text3DFontMode;
  font?: Text3DFont;
  fontFamily?: string;
  fontWeight?: Text3DFontWeight;
  size?: number;
  letterSpacing?: number;
  lineHeight?: number;
  alignment?: Text3DAlignment;
  material?: Text3DMaterial;
  colorMode?: Text3DColorMode;
  colors?: readonly string[];
  metalness?: number;
  roughness?: number;
  clearcoat?: number;
  clearcoatRoughness?: number;
  transmission?: number;
  ior?: number;
  thickness?: number;
  glow?: number;
  depth?: number;
  bevelEnabled?: boolean;
  bevelSize?: number;
  bevelThickness?: number;
  bevelSegments?: number;
  curveSegments?: number;
  environment?: Text3DEnvironment;
  lightIntensity?: number;
  ambientIntensity?: number;
  lightAngle?: number;
  reflectionStrength?: number;
  shadow?: boolean;
  rotationX?: number;
  rotationY?: number;
  rotationZ?: number;
  zoom?: number;
  interactive?: boolean;
  poseMode?: Text3DPoseMode;
  /** @deprecated Use `poseMode="auto-rotate"`. */
  autoRotate?: boolean;
  autoRotateSpeed?: number;
  damping?: number;
  background?: boolean;
  backgroundColor?: string;
  quality?: Text3DQuality;
  paused?: boolean;
  wheelZoom?: Text3DWheelZoom;
  theme?: ThemeInput;
  onPoseChange?: (pose: Text3DPose) => void;
}

const TEXT_3D_GEOMETRY_REBUILD_DELAY_MS = 300;
const TEXT_3D_TEXT_REBUILD_DELAY_MS = 700;

const overlayStyle = `.text-3d-fallback-text{font-size:clamp(2rem,12vw,9rem)}
[data-balsa="text-3d"] canvas{touch-action:none}
@media (forced-colors: active){
  [data-balsa="text-3d"] canvas{display:none}
  [data-balsa="text-3d"] .text-3d-fallback-text{background:none;color:CanvasText}
}`;

const overrideKeys = [
  "seed", "text", "fontMode", "font", "fontFamily", "fontWeight", "size", "letterSpacing",
  "lineHeight", "alignment", "material", "colorMode", "colors", "metalness",
  "roughness", "clearcoat", "clearcoatRoughness", "transmission", "ior",
  "thickness", "glow", "depth", "bevelEnabled", "bevelSize", "bevelThickness",
  "bevelSegments", "curveSegments", "environment", "lightIntensity",
  "ambientIntensity", "lightAngle", "reflectionStrength", "shadow", "rotationX",
  "rotationY", "rotationZ", "zoom", "interactive", "poseMode", "autoRotate",
  "autoRotateSpeed", "damping", "background", "backgroundColor", "quality",
] as const satisfies readonly (keyof Text3DDirectOverrides)[];

const gradientBlobs = {
  pattern: "blobs" as const,
  ...gradientBackgroundPatternDefaults.blobs,
  patternComplexity: 4,
  scale: 0.7,
  softness: 0.95,
  warp: 0.5,
  wave: 0.9,
};

interface ContextSnapshot {
  paletteAvailable: boolean;
  paletteColors: Text3DColors;
  paletteEnvironment: Text3DEnvironmentColors;
  themeFontFamily?: string;
}

interface RuntimeState {
  renderer?: Text3DRenderer;
  loadedFont?: Font;
  fontRequest: number;
  contextFrame: number;
  geometryRebuildTimer?: ReturnType<typeof setTimeout>;
  appliedGeometrySignature: string;
  appliedText: string;
  resizeObserver?: ResizeObserver;
  intersectionObserver?: IntersectionObserver;
  contextObserver?: MutationObserver;
  motionQuery?: MediaQueryList;
  documentVisible: boolean;
  inViewport: boolean;
  reducedMotion: boolean;
  rendererAvailable: boolean;
}

function directOverridesFrom(
  props: Text3DDirectOverrides & { overrides?: Text3DDirectOverrides },
): Text3DDirectOverrides {
  const overrides: Text3DDirectOverrides = { ...props.overrides };
  for (const key of overrideKeys) {
    const value = props[key];
    if (value !== undefined) Object.assign(overrides, { [key]: value });
  }
  return overrides;
}

export const Text3D = forwardRef<Text3DHandle, Text3DProps>(function Text3D(
  rawProps,
  forwardedRef,
) {
  const {
    preset,
    config,
    overrides,
    seed,
    text,
    fontMode,
    font,
    fontFamily,
    fontWeight,
    size,
    letterSpacing,
    lineHeight,
    alignment,
    material,
    colorMode,
    colors,
    metalness,
    roughness,
    clearcoat,
    clearcoatRoughness,
    transmission,
    ior,
    thickness,
    glow,
    depth,
    bevelEnabled,
    bevelSize,
    bevelThickness,
    bevelSegments,
    curveSegments,
    environment,
    lightIntensity,
    ambientIntensity,
    lightAngle,
    reflectionStrength,
    shadow,
    rotationX,
    rotationY,
    rotationZ,
    zoom,
    interactive,
    poseMode,
    autoRotate,
    autoRotateSpeed,
    damping,
    background,
    backgroundColor,
    quality,
    paused = false,
    wheelZoom = "modifier",
    theme: _themeInput,
    onPoseChange,
    className,
    style,
    "data-balsa": _dataBalsa,
    ...domProps
  } = rawProps;
  void _themeInput;
  void _dataBalsa;

  const configuration = useMemo(
    () =>
      resolveText3DConfig({
        preset,
        config,
        overrides: directOverridesFrom({
          overrides,
          seed,
          text,
          fontMode,
          font,
          fontFamily,
          fontWeight,
          size,
          letterSpacing,
          lineHeight,
          alignment,
          material,
          colorMode,
          colors,
          metalness,
          roughness,
          clearcoat,
          clearcoatRoughness,
          transmission,
          ior,
          thickness,
          glow,
          depth,
          bevelEnabled,
          bevelSize,
          bevelThickness,
          bevelSegments,
          curveSegments,
          environment,
          lightIntensity,
          ambientIntensity,
          lightAngle,
          reflectionStrength,
          shadow,
          rotationX,
          rotationY,
          rotationZ,
          zoom,
          interactive,
          poseMode,
          autoRotate,
          autoRotateSpeed,
          damping,
          background,
          backgroundColor,
          quality,
        }),
      }),
    [
      preset, config, overrides, seed, text, fontMode, font, fontFamily, fontWeight,
      size, letterSpacing, lineHeight, alignment, material, colorMode, colors,
      metalness, roughness, clearcoat, clearcoatRoughness, transmission, ior,
      thickness, glow, depth, bevelEnabled, bevelSize, bevelThickness, bevelSegments,
      curveSegments, environment, lightIntensity, ambientIntensity, lightAngle,
      reflectionStrength, shadow, rotationX, rotationY, rotationZ, zoom, interactive,
      poseMode, autoRotate, autoRotateSpeed, damping, background, backgroundColor,
      quality,
    ],
  );

  const rootRef = useRef<HTMLDivElement | null>(null);
  const canvasRef = useRef<HTMLCanvasElement | null>(null);
  const gradientRef = useRef<GradientBackgroundHandle | null>(null);
  const readyRef = useRef(false);
  const contextLostRef = useRef(false);
  const [ready, setReady] = useState(false);
  const [contextLost, setContextLost] = useState(false);
  const [snapshot, setSnapshot] = useState<ContextSnapshot>({
    paletteAvailable: false,
    paletteColors: [...TEXT_3D_DEFAULTS.colors],
    paletteEnvironment: {},
  });
  const snapshotRef = useRef(snapshot);
  const onPoseChangeRef = useRef(onPoseChange);
  onPoseChangeRef.current = onPoseChange;
  const runtime = useRef<RuntimeState>({
    fontRequest: 0,
    contextFrame: 0,
    appliedGeometrySignature: "",
    appliedText: "",
    documentVisible: true,
    inViewport: true,
    reducedMotion: false,
    rendererAvailable: false,
  });
  const latest = useRef({ configuration, paused, wheelZoom });
  latest.current = { configuration, paused, wheelZoom };

  function setReadyState(value: boolean): void {
    readyRef.current = value;
    setReady(value);
  }

  function setContextLostState(value: boolean): void {
    contextLostRef.current = value;
    setContextLost(value);
  }

  function derived(source: BalsaText3DConfig, context: ContextSnapshot) {
    const activeColors = source.colorMode === "palette" && context.paletteAvailable
      ? context.paletteColors
      : source.colors;
    const activeFont = source.fontMode === "theme"
      ? matchText3DFont(context.themeFontFamily, source.font)
      : source.font;
    const activeFontFamily = usesText3DCustomFontFamily(source) ? source.fontFamily : "";
    const activeConfiguration: BalsaText3DConfig = {
      ...source,
      colors: [...activeColors],
      font: activeFont,
    };
    const gradientBackdrop = Boolean(source.background && source.backdrop === "gradient");
    const rendererConfiguration: BalsaText3DConfig = gradientBackdrop
      ? { ...activeConfiguration, background: false }
      : activeConfiguration;
    return {
      activeColors,
      activeFont,
      activeFontFamily,
      activeConfiguration,
      gradientBackdrop,
      rendererConfiguration,
    };
  }

  function updateContext(): void {
    const element = rootRef.current;
    if (!element) return;
    const next: ContextSnapshot = {
      paletteAvailable: hasText3DPalette(element),
      paletteColors: resolveText3DPaletteColors(element, latest.current.configuration.colors),
      paletteEnvironment: resolveText3DPaletteEnvironment(element),
      themeFontFamily: resolveText3DThemeFontFamily(element),
    };
    snapshotRef.current = next;
    setSnapshot(next);
  }

  function shouldAnimate(): boolean {
    return Boolean(
      runtime.current.rendererAvailable
      && readyRef.current
      && !contextLostRef.current
      && !latest.current.paused
      && runtime.current.documentVisible
      && runtime.current.inViewport
      && latest.current.configuration.poseMode !== "static",
    );
  }

  function resizeRenderer(width?: number, height?: number): void {
    const { renderer } = runtime.current;
    const root = rootRef.current;
    if (!renderer || !root) return;
    const bounds = root.getBoundingClientRect();
    renderer.resize(width ?? bounds.width, height ?? bounds.height);
    renderer.render();
  }

  function synchronizeAnimation(): void {
    runtime.current.renderer?.setAnimationActive(shouldAnimate(), runtime.current.reducedMotion);
    if (!shouldAnimate()) runtime.current.renderer?.render();
  }

  function cancelPendingGeometryRebuild(): void {
    if (runtime.current.geometryRebuildTimer === undefined) return;
    clearTimeout(runtime.current.geometryRebuildTimer);
    runtime.current.geometryRebuildTimer = undefined;
  }

  function applyRendererUpdate(): void {
    cancelPendingGeometryRebuild();
    const { renderer, loadedFont } = runtime.current;
    if (!renderer || !loadedFont) return;
    const current = derived(latest.current.configuration, snapshotRef.current);
    renderer.update(
      current.rendererConfiguration,
      loadedFont,
      snapshotRef.current.paletteEnvironment,
    );
    runtime.current.appliedGeometrySignature = text3DGeometrySignature(
      current.rendererConfiguration,
    );
    runtime.current.appliedText = current.rendererConfiguration.text;
    resizeRenderer();
    synchronizeAnimation();
  }

  function flushPendingGeometryRebuild(): void {
    if (runtime.current.geometryRebuildTimer === undefined) return;
    applyRendererUpdate();
  }

  function scheduleRendererUpdate(): void {
    const { renderer, loadedFont } = runtime.current;
    if (!renderer || !loadedFont || contextLostRef.current) return;
    const current = derived(latest.current.configuration, snapshotRef.current);
    if (text3DGeometrySignature(current.rendererConfiguration) === runtime.current.appliedGeometrySignature) {
      applyRendererUpdate();
      return;
    }
    cancelPendingGeometryRebuild();
    const delayMs = current.rendererConfiguration.text !== runtime.current.appliedText
      ? TEXT_3D_TEXT_REBUILD_DELAY_MS
      : TEXT_3D_GEOMETRY_REBUILD_DELAY_MS;
    runtime.current.geometryRebuildTimer = setTimeout(() => {
      runtime.current.geometryRebuildTimer = undefined;
      applyRendererUpdate();
    }, delayMs);
  }

  function createRenderer(): void {
    const canvas = canvasRef.current;
    const root = rootRef.current;
    const loadedFont = runtime.current.loadedFont;
    if (!canvas || !root || !loadedFont) return;
    cancelPendingGeometryRebuild();
    const current = derived(latest.current.configuration, snapshotRef.current);
    try {
      runtime.current.renderer?.dispose();
      runtime.current.renderer = new Text3DRenderer(
        canvas,
        current.rendererConfiguration,
        loadedFont,
        snapshotRef.current.paletteEnvironment,
        (pose) => onPoseChangeRef.current?.(pose),
        latest.current.wheelZoom,
      );
      const bounds = root.getBoundingClientRect();
      runtime.current.renderer.resize(bounds.width, bounds.height);
      runtime.current.renderer.render();
      setReadyState(true);
      runtime.current.rendererAvailable = true;
      setContextLostState(false);
      runtime.current.appliedGeometrySignature = text3DGeometrySignature(
        current.rendererConfiguration,
      );
      runtime.current.appliedText = current.rendererConfiguration.text;
      synchronizeAnimation();
    } catch {
      runtime.current.renderer?.dispose();
      runtime.current.renderer = undefined;
      setReadyState(false);
      runtime.current.rendererAvailable = false;
      runtime.current.appliedGeometrySignature = "";
      runtime.current.appliedText = "";
    }
  }

  async function loadActiveFont(): Promise<Font> {
    const current = derived(latest.current.configuration, snapshotRef.current);
    const family = current.activeFontFamily;
    const weight = latest.current.configuration.fontWeight;
    if (!family) return loadText3DFont(current.activeFont, weight);
    try {
      return await loadText3DRemoteFont(family, weight, latest.current.configuration.text);
    } catch {
      return loadText3DFont(current.activeFont, weight);
    }
  }

  async function synchronizeFont(): Promise<void> {
    const request = ++runtime.current.fontRequest;
    setReadyState(false);
    try {
      const loaded = await loadActiveFont();
      if (request !== runtime.current.fontRequest) return;
      runtime.current.loadedFont = loaded;
      if (runtime.current.renderer) {
        applyRendererUpdate();
        setReadyState(true);
      } else {
        createRenderer();
      }
    } catch {
      if (request !== runtime.current.fontRequest) return;
      cancelPendingGeometryRebuild();
      runtime.current.loadedFont = undefined;
      runtime.current.renderer?.dispose();
      runtime.current.renderer = undefined;
      runtime.current.rendererAvailable = false;
      setReadyState(false);
      runtime.current.appliedGeometrySignature = "";
      runtime.current.appliedText = "";
    }
  }

  function renderStill(): void {
    flushPendingGeometryRebuild();
    runtime.current.renderer?.render();
  }

  function resetPose(): void {
    runtime.current.renderer?.resetPose();
  }

  function captureSize(options: Text3DCaptureOptions): { width: number; height: number } {
    const bound = (value: number): number => Math.min(4096, Math.max(320, Math.round(value)));
    return {
      width: bound(options.width ?? rootRef.current?.clientWidth ?? 1280),
      height: bound(options.height ?? rootRef.current?.clientHeight ?? 720),
    };
  }

  interface DecodedPng {
    source: ImageBitmap | HTMLImageElement;
    close: () => void;
  }

  async function decodePng(blob: Blob): Promise<DecodedPng> {
    if (typeof createImageBitmap === "function") {
      const bitmap = await createImageBitmap(blob);
      return { source: bitmap, close: () => bitmap.close() };
    }
    const url = URL.createObjectURL(blob);
    const image = new Image();
    try {
      await new Promise<void>((resolve, reject) => {
        image.onload = () => resolve();
        image.onerror = () => reject(new Error("The captured PNG could not be decoded."));
        image.src = url;
      });
      return { source: image, close: () => URL.revokeObjectURL(url) };
    } catch (error) {
      URL.revokeObjectURL(url);
      throw error;
    }
  }

  async function drawGradientBackdrop(
    context: CanvasRenderingContext2D,
    width: number,
    height: number,
  ): Promise<void> {
    await Promise.resolve();
    const field = gradientRef.current;
    if (!field) throw new Error("The gradient backdrop is not ready for capture.");
    const image = await decodePng(await field.capturePng({ width, height }));
    try {
      context.drawImage(image.source, 0, 0, width, height);
    } finally {
      image.close();
    }
  }

  async function captureFallbackPng(options: Text3DCaptureOptions): Promise<Blob> {
    const layer = options.layer ?? "composite";
    const { width, height } = captureSize(options);
    const output = document.createElement("canvas");
    output.width = width;
    output.height = height;
    const context = output.getContext("2d");
    if (!context) throw new Error("PNG export is unavailable in this browser.");
    const current = derived(latest.current.configuration, snapshotRef.current);
    const lines = latest.current.configuration.text.split("\n");
    if (layer !== "text") {
      if (current.gradientBackdrop) {
        await drawGradientBackdrop(context, width, height);
      } else if (options.opaque || latest.current.configuration.background) {
        context.fillStyle = latest.current.configuration.backgroundColor;
        context.fillRect(0, 0, width, height);
      }
    }
    if (layer !== "gradient") {
      context.fillStyle = current.activeColors[0] ?? "#000000";
      context.textAlign = "center";
      context.textBaseline = "middle";
      context.font = `700 ${Math.max(32, height / Math.max(2, lines.length + 1))}px ${snapshotRef.current.themeFontFamily ?? "sans-serif"}`;
      const gap = height / Math.max(2, lines.length + 1);
      lines.forEach((line, index) => context.fillText(line, width / 2, gap * (index + 1)));
    }
    return new Promise((resolve, reject) => output.toBlob((blob) => {
      if (blob) resolve(blob);
      else reject(new Error("The browser could not encode the fallback PNG."));
    }, "image/png"));
  }

  async function captureGradientPng(
    options: Text3DCaptureOptions,
    scene: Text3DRenderer,
  ): Promise<Blob> {
    const layer = options.layer ?? "composite";
    const { width, height } = captureSize(options);
    const field = gradientRef.current;
    if (!field) throw new Error("The gradient backdrop is not ready for capture.");
    if (layer === "gradient") return field.capturePng({ width, height });
    if (layer === "text") {
      return scene.capturePng({ ...options, width, height, opaque: false });
    }
    const [fieldBlob, textBlob] = await Promise.all([
      field.capturePng({ width, height }),
      scene.capturePng({ ...options, width, height, opaque: false }),
    ]);
    const output = document.createElement("canvas");
    output.width = width;
    output.height = height;
    const context = output.getContext("2d");
    if (!context) throw new Error("PNG export is unavailable in this browser.");
    const [fieldImage, textImage] = await Promise.all([
      decodePng(fieldBlob),
      decodePng(textBlob),
    ]);
    try {
      context.drawImage(fieldImage.source, 0, 0, width, height);
      context.drawImage(textImage.source, 0, 0, width, height);
    } finally {
      fieldImage.close();
      textImage.close();
    }
    return new Promise((resolve, reject) => output.toBlob((blob) => {
      if (blob) resolve(blob);
      else reject(new Error("The browser could not encode the 3D text PNG."));
    }, "image/png"));
  }

  async function capturePng(options: Text3DCaptureOptions = {}): Promise<Blob> {
    flushPendingGeometryRebuild();
    const layer = options.layer ?? "composite";
    const current = derived(latest.current.configuration, snapshotRef.current);
    if (!runtime.current.renderer) return captureFallbackPng(options);
    if (layer === "text") {
      return runtime.current.renderer.capturePng({ ...options, opaque: false });
    }
    if (layer === "gradient") {
      if (current.gradientBackdrop) {
        const field = gradientRef.current;
        if (!field) throw new Error("The gradient backdrop is not ready for capture.");
        const { width, height } = captureSize(options);
        return field.capturePng({ width, height });
      }
      return captureFallbackPng({ ...options, layer: "gradient" });
    }
    if (current.gradientBackdrop) return captureGradientPng(options, runtime.current.renderer);
    return runtime.current.renderer.capturePng(options);
  }

  useImperativeHandle(forwardedRef, () => ({ capturePng, renderStill, resetPose }));

  const current = derived(configuration, snapshot);
  const fontRequestKey = [
    current.activeFontFamily,
    current.activeFont,
    configuration.fontWeight,
    current.activeFontFamily ? configuration.text : "",
  ].join("|");

  useLayoutEffect(() => {
    const canvas = canvasRef.current;
    const root = rootRef.current;
    runtime.current.documentVisible = document.visibilityState !== "hidden";
    updateContext();

    function handleVisibilityChange(): void {
      runtime.current.documentVisible = document.visibilityState !== "hidden";
      synchronizeAnimation();
    }
    function handleMotionChange(event: MediaQueryListEvent | MediaQueryList): void {
      runtime.current.reducedMotion = event.matches;
      synchronizeAnimation();
    }
    function handleContextLost(event: Event): void {
      event.preventDefault();
      cancelPendingGeometryRebuild();
      setContextLostState(true);
      setReadyState(false);
      synchronizeAnimation();
    }
    function handleContextRestored(): void {
      setContextLostState(false);
      queueMicrotask(createRenderer);
    }
    function queueContextUpdate(): void {
      if (runtime.current.contextFrame) return;
      runtime.current.contextFrame = requestAnimationFrame(() => {
        runtime.current.contextFrame = 0;
        updateContext();
      });
    }

    canvas?.addEventListener("webglcontextlost", handleContextLost);
    canvas?.addEventListener("webglcontextrestored", handleContextRestored);
    document.addEventListener("visibilitychange", handleVisibilityChange);
    if (typeof window.matchMedia === "function") {
      runtime.current.motionQuery = window.matchMedia("(prefers-reduced-motion: reduce)");
      runtime.current.reducedMotion = runtime.current.motionQuery.matches;
      runtime.current.motionQuery.addEventListener("change", handleMotionChange);
    }
    if (typeof ResizeObserver !== "undefined") {
      runtime.current.resizeObserver = new ResizeObserver((entries) => {
        const entry = entries[0];
        if (entry) resizeRenderer(entry.contentRect.width, entry.contentRect.height);
      });
      if (root) runtime.current.resizeObserver.observe(root);
    }
    if (typeof IntersectionObserver !== "undefined") {
      runtime.current.intersectionObserver = new IntersectionObserver((entries) => {
        runtime.current.inViewport = entries[0]?.isIntersecting ?? true;
        synchronizeAnimation();
      }, { rootMargin: "96px" });
      if (root) runtime.current.intersectionObserver.observe(root);
    }
    runtime.current.contextObserver = new MutationObserver(queueContextUpdate);
    let boundary: HTMLElement | null = root;
    while (boundary) {
      runtime.current.contextObserver.observe(boundary, {
        attributes: true,
        attributeFilter: ["data-palette", "data-balsa-theme", "class", "style"],
      });
      boundary = boundary.parentElement;
    }
    void synchronizeFont();

    return () => {
      runtime.current.fontRequest += 1;
      cancelPendingGeometryRebuild();
      if (runtime.current.contextFrame) cancelAnimationFrame(runtime.current.contextFrame);
      runtime.current.contextFrame = 0;
      runtime.current.resizeObserver?.disconnect();
      runtime.current.intersectionObserver?.disconnect();
      runtime.current.contextObserver?.disconnect();
      runtime.current.motionQuery?.removeEventListener("change", handleMotionChange);
      document.removeEventListener("visibilitychange", handleVisibilityChange);
      canvas?.removeEventListener("webglcontextlost", handleContextLost);
      canvas?.removeEventListener("webglcontextrestored", handleContextRestored);
      runtime.current.renderer?.dispose();
      runtime.current.renderer = undefined;
      runtime.current.loadedFont = undefined;
      runtime.current.rendererAvailable = false;
      runtime.current.appliedGeometrySignature = "";
      runtime.current.appliedText = "";
    };
  }, []);

  const skipFontWatch = useRef(true);
  useLayoutEffect(() => {
    if (skipFontWatch.current) {
      skipFontWatch.current = false;
      return;
    }
    void synchronizeFont();
  }, [fontRequestKey]);

  const skipConfigWatch = useRef(true);
  useLayoutEffect(() => {
    if (skipConfigWatch.current) {
      skipConfigWatch.current = false;
      return;
    }
    scheduleRendererUpdate();
    synchronizeAnimation();
    runtime.current.renderer?.setWheelZoom(wheelZoom);
  }, [configuration, snapshot, paused, wheelZoom]);

  const namedGradientPreset = configuration.gradientPreset || undefined;
  const gradientBackdropBind = namedGradientPreset
    ? { preset: namedGradientPreset }
    : {
        colorMode: "custom" as const,
        colors: text3DGradientColors(current.activeColors, configuration.reflections),
        pattern: gradientBlobs.pattern,
        patternComplexity: gradientBlobs.patternComplexity,
        scale: gradientBlobs.scale,
        softness: gradientBlobs.softness,
        warp: gradientBlobs.warp,
        wave: gradientBlobs.wave,
        seed: configuration.seed,
      };
  const lines = configuration.text.split("\n");
  const canvasVisible = ready && !contextLost;
  const fallbackStyle = {
    ...buildText3DFallbackStyle(current.activeColors),
    fontFamily: current.activeFontFamily
      ? `${JSON.stringify(current.activeFontFamily)}, sans-serif`
      : configuration.fontMode === "theme"
        ? snapshot.themeFontFamily
        : undefined,
  } as CSSProperties;

  return (
    <>
      <style>{overlayStyle}</style>
      <div
        ref={rootRef}
        {...domProps}
        data-balsa="text-3d"
        className={mergeClasses(
          "relative isolate grid h-full w-full place-items-center overflow-hidden",
          className,
        )}
        style={style}
      >
        <span className="sr-only">{configuration.text}</span>
        {current.gradientBackdrop ? (
          <GradientBackground
            ref={gradientRef}
            data-balsa-text-3d-gradient=""
            {...gradientBackdropBind}
            quality={configuration.quality}
            paused={paused}
            className="absolute inset-0 -z-10"
          />
        ) : null}
        <div
          className={mergeClasses(
            "text-3d-fallback absolute inset-0 grid place-items-center transition-opacity",
            canvasVisible ? "pointer-events-none opacity-0" : "opacity-100",
          )}
          aria-hidden="true"
        >
          <p
            className="text-3d-fallback-text m-0 select-text text-center font-balsa-title font-semibold leading-tight"
            style={fallbackStyle}
          >
            {lines.map((line, index) => (
              <span key={`${index}-${line}`} className="block">{line}</span>
            ))}
          </p>
        </div>
        <canvas
          ref={canvasRef}
          className={mergeClasses(
            "absolute inset-0 block size-full transition-opacity",
            canvasVisible ? "opacity-100" : "opacity-0",
          )}
          aria-hidden="true"
        />
      </div>
    </>
  );
});

// src/components/ui/Text3D.vue
<script setup lang="ts">
import {
  computed,
  nextTick,
  onBeforeUnmount,
  onMounted,
  ref,
  watch,
} from "vue";
import {
  TEXT_3D_DEFAULTS,
  buildText3DFallbackStyle,
  hasText3DPalette,
  matchText3DFont,
  resolveText3DConfig,
  resolveText3DPaletteColors,
  resolveText3DPaletteEnvironment,
  resolveText3DThemeFontFamily,
  text3DGradientColors,
  usesText3DCustomFontFamily,
  type BalsaText3DConfig,
  type Text3DAlignment,
  type Text3DCaptureOptions,
  type Text3DColorMode,
  type Text3DColors,
  type Text3DConfigInput,
  type Text3DDirectOverrides,
  type Text3DEnvironment,
  type Text3DFont,
  type Text3DFontMode,
  type Text3DFontWeight,
  type Text3DMaterial,
  type Text3DPose,
  type Text3DPoseMode,
  type Text3DPresetName,
  type Text3DQuality,
  type Text3DWheelZoom,
} from "./text-3d";
import { loadText3DFont, loadText3DRemoteFont } from "./text-3d-fonts";
import {
  Text3DRenderer,
  text3DGeometrySignature,
  type Text3DEnvironmentColors,
} from "./text-3d-renderer";
import GradientBackground from "./GradientBackground.vue";
import {
  gradientBackgroundPatternDefaults,
  type GradientBackgroundExposed,
} from "./gradient-background";
import type { Font } from "three/examples/jsm/loaders/FontLoader.js";

const props = withDefaults(
  defineProps<{
    preset?: Text3DPresetName;
    config?: Text3DConfigInput;
    overrides?: Text3DDirectOverrides;
    seed?: number;
    text?: string;
    fontMode?: Text3DFontMode;
    font?: Text3DFont;
    fontFamily?: string;
    fontWeight?: Text3DFontWeight;
    size?: number;
    letterSpacing?: number;
    lineHeight?: number;
    alignment?: Text3DAlignment;
    material?: Text3DMaterial;
    colorMode?: Text3DColorMode;
    colors?: readonly string[];
    metalness?: number;
    roughness?: number;
    clearcoat?: number;
    clearcoatRoughness?: number;
    transmission?: number;
    ior?: number;
    thickness?: number;
    glow?: number;
    depth?: number;
    bevelEnabled?: boolean;
    bevelSize?: number;
    bevelThickness?: number;
    bevelSegments?: number;
    curveSegments?: number;
    environment?: Text3DEnvironment;
    lightIntensity?: number;
    ambientIntensity?: number;
    lightAngle?: number;
    reflectionStrength?: number;
    shadow?: boolean;
    rotationX?: number;
    rotationY?: number;
    rotationZ?: number;
    zoom?: number;
    interactive?: boolean;
    poseMode?: Text3DPoseMode;
    /** @deprecated Use `poseMode="auto-rotate"`. */
    autoRotate?: boolean;
    autoRotateSpeed?: number;
    damping?: number;
    background?: boolean;
    backgroundColor?: string;
    quality?: Text3DQuality;
    paused?: boolean;
    /**
     * `modifier` (default) zooms only with Ctrl/Cmd + wheel so a hero in a
     * scrolling page never traps the reader. `always` zooms on a plain wheel;
     * 3D Text Studio opts into that because its preview fills the viewport.
     */
    wheelZoom?: Text3DWheelZoom;
  }>(),
  {
    preset: undefined,
    config: undefined,
    overrides: undefined,
    seed: undefined,
    text: undefined,
    fontMode: undefined,
    font: undefined,
    fontFamily: undefined,
    fontWeight: undefined,
    size: undefined,
    letterSpacing: undefined,
    lineHeight: undefined,
    alignment: undefined,
    material: undefined,
    colorMode: undefined,
    colors: undefined,
    metalness: undefined,
    roughness: undefined,
    clearcoat: undefined,
    clearcoatRoughness: undefined,
    transmission: undefined,
    ior: undefined,
    thickness: undefined,
    glow: undefined,
    depth: undefined,
    bevelEnabled: undefined,
    bevelSize: undefined,
    bevelThickness: undefined,
    bevelSegments: undefined,
    curveSegments: undefined,
    environment: undefined,
    lightIntensity: undefined,
    ambientIntensity: undefined,
    lightAngle: undefined,
    reflectionStrength: undefined,
    shadow: undefined,
    rotationX: undefined,
    rotationY: undefined,
    rotationZ: undefined,
    zoom: undefined,
    interactive: undefined,
    poseMode: undefined,
    autoRotate: undefined,
    autoRotateSpeed: undefined,
    damping: undefined,
    background: undefined,
    backgroundColor: undefined,
    quality: undefined,
    paused: false,
    wheelZoom: "modifier",
  },
);

const emit = defineEmits<{
  "update:pose": [pose: Text3DPose];
}>();

const root = ref<HTMLElement | null>(null);
const canvas = ref<HTMLCanvasElement | null>(null);
const gradient = ref<GradientBackgroundExposed | null>(null);
const ready = ref(false);
const rendererAvailable = ref(false);
const contextLost = ref(false);
const documentVisible = ref(true);
const inViewport = ref(true);
const reducedMotion = ref(false);
const paletteAvailable = ref(false);
const paletteColors = ref<Text3DColors>([...TEXT_3D_DEFAULTS.colors]);
const paletteEnvironment = ref<Text3DEnvironmentColors>({});
const themeFontFamily = ref<string>();
const loadedFont = ref<Font>();

let renderer: Text3DRenderer | undefined;
let resizeObserver: ResizeObserver | undefined;
let intersectionObserver: IntersectionObserver | undefined;
let contextObserver: MutationObserver | undefined;
let motionQuery: MediaQueryList | undefined;
let contextFrame = 0;
let fontRequest = 0;
/**
 * Geometry rebuilds are a per-glyph Poisson/Jacobi solve, up to 640 iterations
 * at high quality. Slider drags arrive a few milliseconds apart, so 300ms
 * coalesces a continuous stream without making the last tick feel abandoned.
 * Typing has natural 150–300ms gaps between keystrokes, so that same interval
 * fires mid-word and rebuilds every glyph repeatedly. Text therefore waits
 * 700ms -- long enough to land after a pause, not between characters. One
 * timer, two intervals: the delay is chosen when scheduling by whether the
 * pending `text` differs from the last applied one. A second timer would add
 * a second flush path and put the flush-before-capture guarantee at risk.
 */
const TEXT_3D_GEOMETRY_REBUILD_DELAY_MS = 300;
const TEXT_3D_TEXT_REBUILD_DELAY_MS = 700;
// Declared and assigned through the same bare setTimeout, so the two agree
// whichever one is in scope. Assigning from window.setTimeout does not:
// `window` is `Window & typeof globalThis`, so in a project with @types/node
// the call resolves to Node's and returns a Timeout the DOM annotation rejects.
let geometryRebuildTimer: ReturnType<typeof setTimeout> | undefined;
let appliedGeometrySignature = "";
let appliedText = "";

const directOverrides = computed<Text3DDirectOverrides>(() => {
  const overrides: Text3DDirectOverrides = { ...props.overrides };
  const keys = [
    "seed", "text", "fontMode", "font", "fontFamily", "fontWeight", "size", "letterSpacing",
    "lineHeight", "alignment", "material", "colorMode", "colors", "metalness",
    "roughness", "clearcoat", "clearcoatRoughness", "transmission", "ior",
    "thickness", "glow", "depth", "bevelEnabled", "bevelSize", "bevelThickness",
    "bevelSegments", "curveSegments", "environment", "lightIntensity",
    "ambientIntensity", "lightAngle", "reflectionStrength", "shadow", "rotationX",
    "rotationY", "rotationZ", "zoom", "interactive", "poseMode", "autoRotate", "autoRotateSpeed",
    "damping", "background", "backgroundColor", "quality",
  ] as const satisfies readonly (keyof Text3DDirectOverrides)[];
  for (const key of keys) {
    const value = props[key];
    if (value !== undefined) Object.assign(overrides, { [key]: value });
  }
  return overrides;
});

const configuration = computed<BalsaText3DConfig>(() =>
  resolveText3DConfig({
    preset: props.preset,
    config: props.config,
    overrides: directOverrides.value,
  }),
);
const activeColors = computed(() =>
  configuration.value.colorMode === "palette" && paletteAvailable.value
    ? paletteColors.value
    : configuration.value.colors,
);
const activeFont = computed<Text3DFont>(() =>
  configuration.value.fontMode === "theme"
    ? matchText3DFont(themeFontFamily.value, configuration.value.font)
    : configuration.value.font,
);
/**
 * The remote family this scene draws, or `""` for a shipped typeface. Only a
 * pinned family qualifies: `fontMode: "theme"` resolves through the generated
 * set, which cannot name a face the project has not installed.
 */
const activeFontFamily = computed(() =>
  usesText3DCustomFontFamily(configuration.value) ? configuration.value.fontFamily : "",
);
const activeConfiguration = computed<BalsaText3DConfig>(() => ({
  ...configuration.value,
  colors: [...activeColors.value],
  font: activeFont.value,
}));
/**
 * A real gradient field, not a painted approximation: the WebGL text sits over
 * an actual `GradientBackground`, which is the only way the backdrop a glass
 * surface refracts is the same field a consumer gets outside the studio.
 */
const gradientBackdrop = computed(() =>
  configuration.value.background && configuration.value.backdrop === "gradient",
);
/**
 * The field is the room made visible: the light cards first, then as many
 * material colours as the stop budget still has room for. Truncating the
 * other way dropped the pink card from liquid-chrome's surround.
 */
const gradientColors = computed(() =>
  text3DGradientColors(activeColors.value, configuration.value.reflections),
);
/**
 * Softboxes, not wallpaper. Specular metal is a mirror of large diffused
 * area lights — the same key/fill/rim/accent set `TEXT_3D_MAXIMUM_REFLECTIONS`
 * already encodes as four cards — so the field uses `blobs` rather than the
 * ribbon default. Starting from `gradientBackgroundPatternDefaults.blobs`,
 * complexity drops so each pool is a fixture rather than a scatter, scale
 * drops so they fill the frame like a cyc wall, and warp/wave drop so the
 * pools stay round and out of focus instead of streaking into a pattern.
 */
const gradientBlobs = {
  pattern: "blobs" as const,
  ...gradientBackgroundPatternDefaults.blobs,
  patternComplexity: 4,
  scale: 0.7,
  softness: 0.95,
  warp: 0.5,
  wave: 0.9,
};
/**
 * A named gradient preset replaces the derived blobs room. Empty/absent keeps
 * today's immersive light-source field built from this scene's own colours.
 */
const namedGradientPreset = computed(() =>
  configuration.value.gradientPreset || undefined,
);
const gradientBackdropBind = computed(() =>
  namedGradientPreset.value
    ? { preset: namedGradientPreset.value }
    : {
        colorMode: "custom" as const,
        colors: gradientColors.value,
        pattern: gradientBlobs.pattern,
        patternComplexity: gradientBlobs.patternComplexity,
        scale: gradientBlobs.scale,
        softness: gradientBlobs.softness,
        warp: gradientBlobs.warp,
        wave: gradientBlobs.wave,
        seed: configuration.value.seed,
      },
);
/**
 * What the renderer is actually given. Under a gradient backdrop the canvas has
 * to clear to transparent so the field below shows through, and `background`
 * is exactly the flag the renderer reads to decide that -- so it is turned off
 * here rather than in the configuration the rest of the component reports.
 */
const rendererConfiguration = computed<BalsaText3DConfig>(() =>
  gradientBackdrop.value
    ? { ...activeConfiguration.value, background: false }
    : activeConfiguration.value,
);
const fallbackStyle = computed(() => ({
  ...buildText3DFallbackStyle(activeColors.value),
  // A pinned remote family is named here too, so the flat text a reader sees
  // before -- or instead of -- the geometry is set in the family they asked
  // for whenever the browser has it. It is a companion to the real outlines,
  // never a substitute for them.
  fontFamily: activeFontFamily.value
    ? `${JSON.stringify(activeFontFamily.value)}, sans-serif`
    : configuration.value.fontMode === "theme"
      ? themeFontFamily.value
      : undefined,
}));
const lines = computed(() => configuration.value.text.split("\n"));
const canvasClasses = computed(() => [
  "absolute inset-0 block size-full transition-opacity",
  ready.value && !contextLost.value ? "opacity-100" : "opacity-0",
]);
const fallbackClasses = computed(() => [
  "text-3d-fallback absolute inset-0 grid place-items-center transition-opacity",
  ready.value && !contextLost.value ? "pointer-events-none opacity-0" : "opacity-100",
]);
const shouldAnimate = computed(() =>
  Boolean(
    rendererAvailable.value
    && ready.value
    && !contextLost.value
    && !props.paused
    && documentVisible.value
    && inViewport.value
    && configuration.value.poseMode !== "static",
  ),
);

function updateContext(): void {
  const element = root.value;
  if (!element) return;
  paletteAvailable.value = hasText3DPalette(element);
  paletteColors.value = resolveText3DPaletteColors(element, configuration.value.colors);
  paletteEnvironment.value = resolveText3DPaletteEnvironment(element);
  themeFontFamily.value = resolveText3DThemeFontFamily(element);
}

function queueContextUpdate(): void {
  if (contextFrame) return;
  contextFrame = requestAnimationFrame(() => {
    contextFrame = 0;
    updateContext();
  });
}

function resizeRenderer(width?: number, height?: number): void {
  if (!renderer || !root.value) return;
  const bounds = root.value.getBoundingClientRect();
  renderer.resize(width ?? bounds.width, height ?? bounds.height);
  renderer.render();
}

function synchronizeAnimation(): void {
  renderer?.setAnimationActive(shouldAnimate.value, reducedMotion.value);
  if (!shouldAnimate.value) renderer?.render();
}

function cancelPendingGeometryRebuild(): void {
  if (geometryRebuildTimer === undefined) return;
  clearTimeout(geometryRebuildTimer);
  geometryRebuildTimer = undefined;
}

function applyRendererUpdate(): void {
  cancelPendingGeometryRebuild();
  if (!renderer || !loadedFont.value) return;
  renderer.update(rendererConfiguration.value, loadedFont.value, paletteEnvironment.value);
  appliedGeometrySignature = text3DGeometrySignature(rendererConfiguration.value);
  appliedText = rendererConfiguration.value.text;
  resizeRenderer();
  synchronizeAnimation();
}

function flushPendingGeometryRebuild(): void {
  if (geometryRebuildTimer === undefined) return;
  applyRendererUpdate();
}

function scheduleRendererUpdate(): void {
  if (!renderer || !loadedFont.value || contextLost.value) return;
  if (text3DGeometrySignature(rendererConfiguration.value) === appliedGeometrySignature) {
    applyRendererUpdate();
    return;
  }
  cancelPendingGeometryRebuild();
  const delayMs = rendererConfiguration.value.text !== appliedText
    ? TEXT_3D_TEXT_REBUILD_DELAY_MS
    : TEXT_3D_GEOMETRY_REBUILD_DELAY_MS;
  geometryRebuildTimer = setTimeout(() => {
    geometryRebuildTimer = undefined;
    applyRendererUpdate();
  }, delayMs);
}

function createRenderer(): void {
  if (!canvas.value || !root.value || !loadedFont.value) return;
  cancelPendingGeometryRebuild();
  try {
    renderer?.dispose();
    renderer = new Text3DRenderer(
      canvas.value,
      rendererConfiguration.value,
      loadedFont.value,
      paletteEnvironment.value,
      (pose) => emit("update:pose", pose),
      props.wheelZoom,
    );
    const bounds = root.value.getBoundingClientRect();
    renderer.resize(bounds.width, bounds.height);
    renderer.render();
    ready.value = true;
    rendererAvailable.value = true;
    contextLost.value = false;
    appliedGeometrySignature = text3DGeometrySignature(rendererConfiguration.value);
    appliedText = rendererConfiguration.value.text;
    synchronizeAnimation();
  } catch {
    renderer?.dispose();
    renderer = undefined;
    ready.value = false;
    rendererAvailable.value = false;
    appliedGeometrySignature = "";
    appliedText = "";
  }
}

/**
 * The outlines this scene needs. A pinned remote family is fetched, subset to
 * the scene's own characters, and converted to a typeface at runtime; anything
 * that goes wrong on that path -- an unknown family, a blocked request, an
 * offline browser -- falls back to the shipped typeface rather than to no
 * geometry at all, so the user keeps a legible 3D scene while they correct the
 * name.
 */
async function loadActiveFont(): Promise<Font> {
  const family = activeFontFamily.value;
  const weight = configuration.value.fontWeight;
  if (!family) return loadText3DFont(activeFont.value, weight);
  try {
    return await loadText3DRemoteFont(family, weight, configuration.value.text);
  } catch {
    return loadText3DFont(activeFont.value, weight);
  }
}

async function synchronizeFont(): Promise<void> {
  const request = ++fontRequest;
  ready.value = false;
  try {
    const font = await loadActiveFont();
    if (request !== fontRequest) return;
    loadedFont.value = font;
    if (renderer) {
      applyRendererUpdate();
      // `ready` was cleared above to hide a stale letterform while the new
      // typeface loads, and only `createRenderer` used to restore it -- so the
      // first font or preset change after mount left the canvas faded out and
      // the flat fallback showing, with a perfectly good scene rendering
      // underneath it. Re-arming here is what makes the swap survivable.
      ready.value = true;
    } else {
      createRenderer();
    }
  } catch {
    if (request !== fontRequest) return;
    cancelPendingGeometryRebuild();
    loadedFont.value = undefined;
    renderer?.dispose();
    renderer = undefined;
    rendererAvailable.value = false;
    ready.value = false;
    appliedGeometrySignature = "";
    appliedText = "";
  }
}

function renderStill(): void {
  flushPendingGeometryRebuild();
  renderer?.render();
}

function resetPose(): void {
  renderer?.resetPose();
}

function handleVisibilityChange(): void {
  documentVisible.value = document.visibilityState !== "hidden";
  synchronizeAnimation();
}

function handleMotionChange(event: MediaQueryListEvent | MediaQueryList): void {
  reducedMotion.value = event.matches;
  synchronizeAnimation();
}

function handleContextLost(event: Event): void {
  event.preventDefault();
  cancelPendingGeometryRebuild();
  contextLost.value = true;
  ready.value = false;
  synchronizeAnimation();
}

function handleContextRestored(): void {
  contextLost.value = false;
  void nextTick(createRenderer);
}

async function captureFallbackPng(options: Text3DCaptureOptions): Promise<Blob> {
  const layer = options.layer ?? "composite";
  const { width, height } = captureSize(options);
  const output = document.createElement("canvas");
  output.width = width;
  output.height = height;
  const context = output.getContext("2d");
  if (!context) throw new Error("PNG export is unavailable in this browser.");
  if (layer !== "text") {
    if (gradientBackdrop.value) {
      await drawGradientBackdrop(context, width, height);
    } else if (options.opaque || configuration.value.background) {
      context.fillStyle = configuration.value.backgroundColor;
      context.fillRect(0, 0, width, height);
    }
  }
  if (layer !== "gradient") {
    context.fillStyle = activeColors.value[0];
    context.textAlign = "center";
    context.textBaseline = "middle";
    context.font = `700 ${Math.max(32, height / Math.max(2, lines.value.length + 1))}px ${themeFontFamily.value ?? "sans-serif"}`;
    const gap = height / Math.max(2, lines.value.length + 1);
    lines.value.forEach((line, index) => context.fillText(line, width / 2, gap * (index + 1)));
  }
  return new Promise((resolve, reject) => output.toBlob((blob) => {
    if (blob) resolve(blob);
    else reject(new Error("The browser could not encode the fallback PNG."));
  }, "image/png"));
}

function captureSize(options: Text3DCaptureOptions): { width: number; height: number } {
  const bound = (value: number): number =>
    Math.min(4096, Math.max(320, Math.round(value)));
  return {
    width: bound(options.width ?? root.value?.clientWidth ?? 1280),
    height: bound(options.height ?? root.value?.clientHeight ?? 720),
  };
}

interface DecodedPng {
  source: ImageBitmap | HTMLImageElement;
  close: () => void;
}

/** Decode a captured layer on browsers both with and without ImageBitmap. */
async function decodePng(blob: Blob): Promise<DecodedPng> {
  if (typeof createImageBitmap === "function") {
    const bitmap = await createImageBitmap(blob);
    return { source: bitmap, close: () => bitmap.close() };
  }
  const url = URL.createObjectURL(blob);
  const image = new Image();
  try {
    await new Promise<void>((resolve, reject) => {
      image.onload = () => resolve();
      image.onerror = () => reject(new Error("The captured PNG could not be decoded."));
      image.src = url;
    });
    return { source: image, close: () => URL.revokeObjectURL(url) };
  } catch (error) {
    URL.revokeObjectURL(url);
    throw error;
  }
}

async function drawGradientBackdrop(
  context: CanvasRenderingContext2D,
  width: number,
  height: number,
): Promise<void> {
  await nextTick();
  const field = gradient.value;
  if (!field) throw new Error("The gradient backdrop is not ready for capture.");
  const image = await decodePng(await field.capturePng({ width, height }));
  try {
    context.drawImage(image.source, 0, 0, width, height);
  } finally {
    image.close();
  }
}

/**
 * A gradient backdrop lives in the DOM behind a transparent canvas, so the
 * canvas alone is not the picture. Both layers are captured at the export size
 * and composited in the same order they stack on screen, which is what makes an
 * exported still match the preview rather than arrive with a hole behind the
 * type.
 */
async function captureGradientPng(
  options: Text3DCaptureOptions,
  scene: Text3DRenderer,
): Promise<Blob> {
  const layer = options.layer ?? "composite";
  const { width, height } = captureSize(options);
  const field = gradient.value;
  if (!field) throw new Error("The gradient backdrop is not ready for capture.");
  if (layer === "gradient") return field.capturePng({ width, height });
  if (layer === "text") {
    return scene.capturePng({ ...options, width, height, opaque: false });
  }
  const [fieldBlob, textBlob] = await Promise.all([
    field.capturePng({ width, height }),
    scene.capturePng({ ...options, width, height, opaque: false }),
  ]);
  const output = document.createElement("canvas");
  output.width = width;
  output.height = height;
  const context = output.getContext("2d");
  if (!context) throw new Error("PNG export is unavailable in this browser.");
  const [fieldImage, textImage] = await Promise.all([
    decodePng(fieldBlob),
    decodePng(textBlob),
  ]);
  try {
    context.drawImage(fieldImage.source, 0, 0, width, height);
    context.drawImage(textImage.source, 0, 0, width, height);
  } finally {
    fieldImage.close();
    textImage.close();
  }
  return new Promise((resolve, reject) => output.toBlob((blob) => {
    if (blob) resolve(blob);
    else reject(new Error("The browser could not encode the 3D text PNG."));
  }, "image/png"));
}

async function capturePng(options: Text3DCaptureOptions = {}): Promise<Blob> {
  flushPendingGeometryRebuild();
  const layer = options.layer ?? "composite";
  if (!renderer) return captureFallbackPng(options);
  if (layer === "text") {
    return renderer.capturePng({ ...options, opaque: false });
  }
  if (layer === "gradient") {
    if (gradientBackdrop.value) {
      const field = gradient.value;
      if (!field) throw new Error("The gradient backdrop is not ready for capture.");
      const { width, height } = captureSize(options);
      return field.capturePng({ width, height });
    }
    return captureFallbackPng({ ...options, layer: "gradient" });
  }
  if (gradientBackdrop.value) return captureGradientPng(options, renderer);
  return renderer.capturePng(options);
}

defineExpose({ capturePng, renderStill, resetPose });

/**
 * What identifies the outlines the scene needs. The text is part of it only
 * under a remote family, whose download is subset to those characters -- a
 * shipped typeface carries the whole charset, so retyping the wordmark there
 * must not reload anything.
 */
const fontRequestKey = computed(() => [
  activeFontFamily.value,
  activeFont.value,
  configuration.value.fontWeight,
  activeFontFamily.value ? configuration.value.text : "",
].join("|"));

watch(fontRequestKey, () => void synchronizeFont());
watch([rendererConfiguration, paletteEnvironment], scheduleRendererUpdate, { deep: true });
watch(shouldAnimate, synchronizeAnimation);
watch(() => props.wheelZoom, (mode) => renderer?.setWheelZoom(mode));

onMounted(() => {
  documentVisible.value = document.visibilityState !== "hidden";
  updateContext();
  canvas.value?.addEventListener("webglcontextlost", handleContextLost);
  canvas.value?.addEventListener("webglcontextrestored", handleContextRestored);
  document.addEventListener("visibilitychange", handleVisibilityChange);
  if (typeof window.matchMedia === "function") {
    motionQuery = window.matchMedia("(prefers-reduced-motion: reduce)");
    reducedMotion.value = motionQuery.matches;
    motionQuery.addEventListener("change", handleMotionChange);
  }
  if (typeof ResizeObserver !== "undefined") {
    resizeObserver = new ResizeObserver((entries) => {
      const entry = entries[0];
      if (entry) resizeRenderer(entry.contentRect.width, entry.contentRect.height);
    });
    if (root.value) resizeObserver.observe(root.value);
  }
  if (typeof IntersectionObserver !== "undefined") {
    intersectionObserver = new IntersectionObserver((entries) => {
      inViewport.value = entries[0]?.isIntersecting ?? true;
      synchronizeAnimation();
    }, { rootMargin: "96px" });
    if (root.value) intersectionObserver.observe(root.value);
  }
  contextObserver = new MutationObserver(queueContextUpdate);
  let boundary: HTMLElement | null = root.value;
  while (boundary) {
    contextObserver.observe(boundary, {
      attributes: true,
      attributeFilter: ["data-palette", "data-balsa-theme", "class", "style"],
    });
    boundary = boundary.parentElement;
  }
  void synchronizeFont();
});

onBeforeUnmount(() => {
  fontRequest += 1;
  cancelPendingGeometryRebuild();
  if (contextFrame) cancelAnimationFrame(contextFrame);
  contextFrame = 0;
  resizeObserver?.disconnect();
  intersectionObserver?.disconnect();
  contextObserver?.disconnect();
  motionQuery?.removeEventListener("change", handleMotionChange);
  document.removeEventListener("visibilitychange", handleVisibilityChange);
  canvas.value?.removeEventListener("webglcontextlost", handleContextLost);
  canvas.value?.removeEventListener("webglcontextrestored", handleContextRestored);
  renderer?.dispose();
  renderer = undefined;
  loadedFont.value = undefined;
  rendererAvailable.value = false;
  appliedGeometrySignature = "";
  appliedText = "";
});
</script>

<template>
  <div
    ref="root"
    data-balsa="text-3d"
    class="relative isolate grid h-full w-full place-items-center overflow-hidden"
  >
    <span class="sr-only">{{ configuration.text }}</span>
    <!-- Behind everything, including the flat fallback: it is the room the
         scene is in, not a decoration on the canvas. -->
    <GradientBackground
      v-if="gradientBackdrop"
      ref="gradient"
      data-balsa-text-3d-gradient
      v-bind="gradientBackdropBind"
      :quality="configuration.quality"
      :paused="paused"
      class="absolute inset-0 -z-10"
    />
    <div :class="fallbackClasses" aria-hidden="true">
      <p class="text-3d-fallback-text m-0 select-text text-center font-balsa-title font-semibold leading-tight" :style="fallbackStyle">
        <span v-for="(line, index) in lines" :key="index" class="block">{{ line }}</span>
      </p>
    </div>
    <canvas ref="canvas" :class="canvasClasses" aria-hidden="true" />
  </div>
</template>

<style scoped>
.text-3d-fallback-text {
  font-size: clamp(2rem, 12vw, 9rem);
}

canvas {
  touch-action: none;
}

@media (forced-colors: active) {
  canvas {
    display: none;
  }

  .text-3d-fallback-text {
    background: none;
    color: CanvasText;
  }
}
</style>
